export { createExecutiveDashboardService } from './executive-dashboard.service';
export { createAcademicAnalyticsService } from './academic-analytics.service';
export { createFinancialAnalyticsService } from './financial-analytics.service';
export { createHrAnalyticsService } from './hr-analytics.service';
export { createStudentAnalyticsService } from './student-analytics.service';
export { createTeacherAnalyticsService } from './teacher-analytics.service';
export { createParentAnalyticsService } from './parent-analytics.service';
export { createPredictiveAiService } from './predictive-ai.service';
export { createReportService } from './report.service';
export { createDashboardService } from './dashboard.service';
export { createWidgetService } from './widget.service';
export { createChartService } from './chart.service';
export { createExportService } from './export.service';
export { createScheduledReportService } from './scheduled-report.service';
export { createDataWarehouseService } from './data-warehouse.service';
export { createKpiService } from './kpi.service';
export { createSnapshotService } from './snapshot.service';
export { createAggregationService } from './aggregation.service';
export { createCacheService } from './cache.service';
export { createPermissionService } from './permission.service';
export { createEventService } from './event.service';
export { createGeoAnalyticsService } from './geo-analytics.service';
export { createHeatmapAnalyticsService } from './heatmap-analytics.service';
export { createFunnelAnalyticsService } from './funnel-analytics.service';
export { createTimelineAnalyticsService } from './timeline-analytics.service';
export { createCohortService } from './cohort.service';
export { createComparisonService } from './comparison.service';
export { createTrendService } from './trend.service';
export { createAnomalyService } from './anomaly.service';
export { createBenchmarkService } from './benchmark.service';
export { createSegmentService } from './segment.service';
export { createCohortRetentionService } from './cohort-retention.service';
export { createRealTimeService } from './real-time.service';
export { createNotificationService } from './notification.service';
export { createReportBuilderService } from './report-builder.service';
export { createDashboardBuilderService } from './dashboard-builder.service';
export { createDataSourceService } from './data-source.service';
export { createEtlService } from './etl.service';
export { createSchedulerService } from './scheduler.service';
export { createAnalyticsPermissionService } from './analytics-permission.service';
export { createImportService } from './export.service';
export { createPermissionService as createPermissionsService } from './permission.service';
export { createSnapshotService as createSnapshotsService } from './snapshot.service';
export { createScheduledReportService as createScheduledReportsService } from './scheduled-report.service';
export { createDataWarehouseService as createFactTableService } from './data-warehouse.service';
export { createDataWarehouseService as createDimensionsService } from './data-warehouse.service';

// Aliases for route imports
export { createExecutiveDashboardService as createExecutiveService } from './executive-dashboard.service';
export { createAcademicAnalyticsService as createAcademicService } from './academic-analytics.service';
export { createFinancialAnalyticsService as createFinancialService } from './financial-analytics.service';
export { createHrAnalyticsService as createHrService } from './hr-analytics.service';
export { createStudentAnalyticsService as createStudentsService } from './student-analytics.service';
export { createTeacherAnalyticsService as createTeachersService } from './teacher-analytics.service';
export { createParentAnalyticsService as createParentsService } from './parent-analytics.service';
export { createPredictiveAiService as createPredictiveService } from './predictive-ai.service';
export { createReportService as createReportsService } from './report.service';
export { createDashboardService as createDashboardsService } from './dashboard.service';
export { createChartService as createChartsService } from './chart.service';
export { createGeoAnalyticsService as createGeoMapService } from './geo-analytics.service';
export { createHeatmapAnalyticsService as createHeatmapService } from './heatmap-analytics.service';
export { createFunnelAnalyticsService as createFunnelService } from './funnel-analytics.service';
export { createTrendService as createTrendAnalyticsService } from './trend.service';
export { createAnomalyService as createAnomalyDetectionService } from './anomaly.service';
export { createBenchmarkService as createBenchmarkAnalyticsService } from './benchmark.service';
export { createSegmentService as createSegmentAnalyticsService } from './segment.service';
export { createCohortService as createCohortAnalyticsService } from './cohort.service';
export { createCohortRetentionService as createCohortRetentionAnalyticsService } from './cohort-retention.service';
export { createRealTimeService as createRealTimeAnalyticsService } from './real-time.service';
export { createNotificationService as createAlertsService } from './notification.service';
export { createReportBuilderService as createReportBuilderAnalyticsService } from './report-builder.service';
export { createDashboardBuilderService as createDashboardBuilderAnalyticsService } from './dashboard-builder.service';
export { createDataSourceService as createDataSourcesService } from './data-source.service';
export { createEtlService as createEtlAnalyticsService } from './etl.service';
export { createSchedulerService as createSchedulerAnalyticsService } from './scheduler.service';
export { createAnalyticsPermissionService as createAnalyticsPermissionsService } from './analytics-permission.service';
export { createComparisonService as createComparisonAnalyticsService } from './comparison.service';
export { createAggregationService as createAggregationAnalyticsService } from './aggregation.service';
export { createCacheService as createCacheAnalyticsService } from './cache.service';
export { createKpiService as createKpiAnalyticsService } from './kpi.service';
export { createEventService as createEventsService } from './event.service';

// Additional aliases for specific route imports
export { createExecutiveDashboardService as createExecutiveDashboardAnalyticsService } from './executive-dashboard.service';
export { createAcademicAnalyticsService as createAcademicAnalyticsAnalyticsService } from './academic-analytics.service';
export { createFinancialAnalyticsService as createFinancialAnalyticsAnalyticsService } from './financial-analytics.service';
export { createHrAnalyticsService as createHrAnalyticsAnalyticsService } from './hr-analytics.service';
export { createStudentAnalyticsService as createStudentAnalyticsAnalyticsService } from './student-analytics.service';
export { createTeacherAnalyticsService as createTeacherAnalyticsAnalyticsService } from './teacher-analytics.service';
export { createParentAnalyticsService as createParentAnalyticsAnalyticsService } from './parent-analytics.service';

// Specific route aliases for missing services
export { createRevenueKpiService } from './kpi.service';
export { createStudentKpiService } from './kpi.service';
export { createTeacherKpiService } from './kpi.service';
export { createAttendanceKpiService } from './kpi.service';
export { createPerformanceKpiService } from './kpi.service';
export { createEnrollmentKpiService } from './kpi.service';
export { createRetentionKpiService } from './kpi.service';
export { createSatisfactionKpiService } from './kpi.service';
export { createCostKpiService } from './kpi.service';
export { createProfitKpiService } from './kpi.service';
export { createSuccessRateService } from './academic-analytics.service';
export { createGradeEvolutionService } from './academic-analytics.service';
export { createClassPerformanceService } from './academic-analytics.service';
export { createSubjectDifficultyService } from './academic-analytics.service';
export { createRevenueTrendService } from './financial-analytics.service';
export { createExpenseTrendService } from './financial-analytics.service';
export { createPaymentStatusService } from './financial-analytics.service';
export { createCashFlowService } from './financial-analytics.service';
export { createBudgetUtilizationService } from './financial-analytics.service';
export { createWorkforceService } from './hr-analytics.service';
export { createTurnoverService } from './hr-analytics.service';
export { createTrainingService } from './hr-analytics.service';
export { createPerformanceRatingService } from './hr-analytics.service';
export { createCompensationService } from './hr-analytics.service';
export { createEnrollmentTrendService } from './student-analytics.service';
export { createDropoutRiskService } from './student-analytics.service';
export { createDisciplineService } from './student-analytics.service';
export { createHealthService } from './student-analytics.service';
export { createParentEngagementService } from './parent-analytics.service';
export { createCommunicationService } from './parent-analytics.service';
export { createDashboardOverviewService } from './dashboard.service';
export { createReportPreviewService } from './report.service';
export { createChartPreviewService } from './chart.service';
export { createDataTableService } from './chart.service';
export { createFilterBuilderService } from './chart.service';
export { createColumnConfigService } from './chart.service';
export { createSortConfigService } from './chart.service';
export { createPaginationService } from './chart.service';
export { createSearchService } from './chart.service';
export { createFiltersService } from './chart.service';
export { createDateRangeService } from './chart.service';
export { createSchoolComparisonService } from './comparison.service';
export { createYearOverYearService } from './comparison.service';
export { createQuarterlyComparisonService } from './comparison.service';
export { createMonthlyComparisonService } from './comparison.service';
export { createDailyComparisonService } from './comparison.service';
export { createGrowthRateService } from './trend.service';
export { createForecastService } from './trend.service';
export { createTargetVsActualService } from './comparison.service';
export { createGeographicDistributionService } from './geo-analytics.service';
export { createDemographicAnalysisService } from './student-analytics.service';
export { createGenderAnalysisService } from './student-analytics.service';
export { createAgeDistributionService } from './student-analytics.service';
export { createSocioeconomicAnalysisService } from './student-analytics.service';
export { createLanguageAnalysisService } from './student-analytics.service';
export { createReligionAnalysisService } from './student-analytics.service';
export { createEthnicAnalysisService } from './student-analytics.service';
export { createUrbanRuralAnalysisService } from './student-analytics.service';
export { createIncomeAnalysisService } from './student-analytics.service';
export { createPovertyAnalysisService } from './student-analytics.service';
export { createEducationLevelAnalysisService } from './student-analytics.service';
export { createLiteracyAnalysisService } from './student-analytics.service';
export { createDigitalLiteracyAnalysisService } from './student-analytics.service';
export { createPredictionsService } from './predictive-ai.service';
export { createRealTimeService as createRealTimeAnalyticsData } from './real-time.service';
export { createRetentionService } from './retention.service';
export { createTimelineService } from './timeline.service';
