export { api } from './api/index';
export {
  sbAuth,
  sbSchools,
  sbStudents,
  sbTeachers,
  sbClasses,
  sbSubjects,
  sbGrades,
  sbAttendance,
  sbPayments,
  sbNotifications,
  sbMessaging,
  sbDashboard,
  sbTransport,
  sbInvitations,
  sbAudit,
  sbAi,
  sbMarketplace,
  sbInvoices,
  sbFinance,
  sbParent,
  sbTeacherCheckin,
  sbImport,
} from './api/supabase-client';
