import React, { createContext, useContext, useCallback, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Lang = 'fr' | 'en';

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, any>> = {
  fr: {
    auth: {
      login: 'Connexion',
      email: 'Email',
      phone: 'Téléphone',
      matricule: 'Matricule',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié ?',
      signIn: 'Se connecter',
      signingIn: 'Connexion...',
      createAccount: 'Créer un compte',
      invitationCode: 'Code d\'invitation',
      activateAccount: 'Activer mon compte',
      schoolCode: 'Code établissement',
      secureAccess: 'Connexion sécurisée. Accès sur invitation uniquement.',
      backToLogin: 'Retour à la connexion',
      enterCredentials: 'Accédez à votre espace EduCI',
    },
    errors: {
      required: 'Veuillez remplir tous les champs.',
      invalidCredentials: 'Identifiants invalides',
      accountLocked: 'Compte verrouillé',
      accountNotActivated: 'Compte non activé. Contactez votre administrateur.',
      serverError: 'Erreur serveur. Réessayez plus tard.',
      networkError: 'Erreur de connexion. Vérifiez votre internet.',
      passwordMismatch: 'Les mots de passe ne correspondent pas.',
      passwordTooShort: 'Le mot de passe doit contenir au moins 8 caractères.',
    },
    success: {
      accountActivated: 'Compte activé avec succès !',
      schoolCreated: 'Établissement créé avec succès !',
      passwordReset: 'Un lien de réinitialisation a été envoyé.',
      attendanceSaved: 'Présences enregistrées avec succès !',
      profileUpdated: 'Profil mis à jour.',
    },
    common: {
      loading: 'Chargement...',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      save: 'Enregistrer',
      delete: 'Supprimer',
      edit: 'Modifier',
      close: 'Fermer',
      search: 'Rechercher...',
      noData: 'Aucune donnée',
      back: 'Retour',
      next: 'Suivant',
      skip: 'Passer',
      getStarted: 'Commencer',
      online: 'En ligne',
      submit: 'Soumettre',
      disconnect: 'Se déconnecter',
      settings: 'Paramètres',
      profile: 'Profil',
      fullName: 'Nom complet',
      phone: 'Téléphone',
      error: 'Erreur',
      success: 'Succès',
      now: 'Maintenant',
      role: 'Membre',
      administrator: 'Administrateur',
      teacher: 'Professeur',
      parent: "Parent d'élève",
      student: 'Élève',
      accountant: 'Comptable',
      secretary: 'Secrétaire',
      censeur: 'Surveillant Général',
      supervisor: 'Surveillant',
      nameEmptyError: 'Le nom ne peut pas être vide.',
      profileUpdateError: 'Impossible de mettre à jour le profil.',
      permissionRequired: 'Permission requise',
      galleryPermissionError: "L'accès à la galerie est nécessaire pour changer votre photo.",
      photoUpdated: 'Photo de profil mise à jour.',
      photoUploadError: 'Impossible de télécharger la photo.',
      course: 'Cours',
      goodMorning: 'Bonjour',
      goodAfternoon: 'Bon après-midi',
      goodEvening: 'Bonsoir',
      seeAll: 'Voir tout',
      dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    },
    onboarding: {
      welcomeTitle: 'Bienvenue sur',
      welcomeSubtitle: 'Connecter écoles, enseignants, élèves et parents dans un seul écosystème numérique.',
      trackTitle: 'Suivez la Réussite Scolaire',
      trackSubtitle: 'Parents et enseignants peuvent suivre les performances académiques, notes et présences en temps réel.',
      paymentsTitle: 'Paiements Sûrs &',
      paymentsHighlight: 'Sécurisés',
      paymentsSubtitle: 'Gérez les frais de scolarité facilement avec Orange Money, MTN MoMo ou Wave.',
      authorizedBy: 'Agréé par le Ministère de l\'Éducation Nationale',
      sampleGrade: 'Note: 18/20',
      sampleSubject: 'Mathématiques',
      sampleAttendance: '95% Présence',
      sampleAttendancePeriod: 'Ce mois-ci',
      paymentLabel: 'PAIEMENT',
      paymentSuccess: 'Réussi',
    },
    home: {
      welcome: 'Bienvenue',
      myJourney: 'Mon Parcours',
      level: 'Niveau 14: Scholar',
      progress: 'objectifs ce mois-ci',
      average: 'Moyenne',
      averageTitle: 'Moyenne Générale',
      rank: 'Rang',
      attendance: 'Présence',
      progression: 'Progression',
      quickActions: 'Actions rapides',
      tasks: 'À faire cette semaine',
      dueDate: 'Échéance',
      aiAssistant: 'Assistant intelligent disponible',
      nextCourse: 'Prochain cours',
      recentMessages: 'Messages récents',
      noTask: 'Aucune tâche',
      noTaskSubtitle: "Vous n'avez pas de tâches en cours",
      noAnnouncement: 'Aucune annonce',
      noAnnouncementSubtitle: "Pas d'annonces pour le moment",
      noMessage: 'Aucun message',
      noMessageSubtitle: "Vous n'avez pas encore de messages",
      newBadge: 'Nouveau',
      unknown: 'Inconnu',
      attendanceHistory: 'Présences',
      present: 'Présent',
      announcements: 'Annonces',
      documents: 'Documents',
      payments: 'Paiements',
      student: 'Élève',
    },
    grades: {
      title: 'Notes',
      subject: 'Matière',
      score: 'Note',
      date: 'Date',
      average: 'Moyenne',
      reportCard: 'Bulletin',
      periods: 'Périodes',
      noGradesSubtitle: 'Les notes seront disponibles prochainement',
      noBulletinsSubtitle: 'Les bulletins seront disponibles prochainement',
    },
    payments: {
      title: 'Paiements',
      payNow: 'Payer maintenant',
      amount: 'Montant',
      method: 'Méthode',
      status: 'Statut',
      paid: 'Payé',
      pending: 'En attente',
      overdue: 'En retard',
      receipt: 'Reçu',
      invoices: 'Factures',
      history: 'Historique',
      noPayments: 'Aucun paiement',
      noPaymentsSubtitle: 'Pas de paiements en cours',
    },
    messages: {
      title: 'Messages',
      allChats: 'Toutes les conversations',
      teachers: 'Enseignants',
      admin: 'Admin',
      transport: 'Transport',
      online: 'En ligne',
      writeMessage: 'Écrire un message...',
      sendMessage: 'Envoyer',
      communitySubtitle: 'Connectez-vous avec votre communauté',
      noConversations: 'Aucune conversation',
      startChat: 'Commencez à discuter',
    },
    transport: {
      title: 'Transport Scolaire',
      subtitle: 'Suivi en temps réel des bus',
      bus: 'Bus',
      route: 'Trajet',
      delay: 'Retard',
      onTime: 'À l\'heure',
      liveTracking: 'Suivi GPS Actif',
      activeBusesCount: 'bus en circulation',
      vehicles: 'Véhicules',
      passengers: 'Passagers',
      driver: 'Chauffeur',
      eta: 'ETA',
      active: 'En circulation',
      enRoute: 'En route',
      maintenance: 'Maintenance',
      notifications: 'Notifications d\'approche',
      notificationsSubtitle: 'Recevez une alerte quand le bus approche de votre arrêt.',
      noBuses: 'Aucun bus disponible',
      noBusesSubtitle: 'Aucun bus n\'est actuellement disponible.',
    },
    marketplace: {
      title: 'Marketplace',
      search: 'Rechercher des ressources...',
      all: 'Tout',
      course: 'Cours',
      quiz: 'Quiz',
      ebook: 'E-Books',
      tutoring: 'Tutorat',
      author: 'Auteur',
      purchases: 'achats',
      confirmPurchase: 'Confirmer l\'achat',
      purchaseConfirmMessage: 'Voulez-vous acheter',
      buy: 'Acheter',
      purchaseSuccess: 'Votre achat a été effectué avec succès !',
      purchaseError: 'Une erreur est survenue lors de l\'achat. Veuillez réessayer.',
      noListings: 'Aucune ressource trouvée',
      noListingsSubtitle: 'Aucune ressource ne correspond à votre recherche.',
    },
    courses: {
      title: 'Mes cours',
      subjects: 'Matières',
      today: "Aujourd'hui",
      totalWeek: 'Total/semaine',
      noCoursesForDay: 'Pas de cours',
      ongoing: 'En cours',
      room: 'Salle',
    },
    ai: {
      title: 'EduCI AI',
      askQuestion: 'Posez une question...',
      send: 'Envoyer',
      suggestions: 'Suggestions',
      resumeCourse: 'Résumer un cours',
      explainExercise: 'Expliquer un exercice',
      generateQuiz: 'Générer un quiz',
      revisionTips: 'Conseils révision',
      resetConfirm: 'Conversation réinitialisée. Comment puis-je t\'aider ?',
      errorMessage: 'Désolé, une erreur s\'est produite. Vérifie ta connexion internet et réessaie.',
      fallbackResponse: 'Je n\'ai pas pu traiter votre demande.',
    },
    examPrep: {
      title: 'Prépare tes examens avec EduCI AI',
      subtitle: 'Quiz interactifs, annales corrigées et assistant IA pour réussir.',
      nationalExams: 'Examens Nationaux',
      continue: 'Continuer',
      resources: 'Ressources Rapides',
      flashcards: 'Fiches Révision',
      videos: 'Cours Vidéos',
      quizzes: 'Quiz Rapides',
      forum: 'Forum Aide',
    },
    attendance_mark: {
      title: 'Marquer les présences',
      selectClass: 'Sélectionnez une classe',
      present: 'Présent',
      absent: 'Absent',
      late: 'Retard',
      validate: 'Valider les présences',
      marked: 'marqués',
      completed: 'Terminé',
    },
    studentSchedule: {
      title: 'Emploi du temps',
    },
    studentAssignments: {
      title: 'Devoirs',
    },
    settings_screen: {
      disconnect: 'Se déconnecter',
      disconnectConfirm: 'Voulez-vous vous déconnecter ?',
      role: 'Rôle',
      email: 'Email',
      school: 'Établissement',
      account: 'Compte',
      editProfile: 'Modifier le profil',
      push: 'Push',
      notifications: 'Notifications',
      security: 'Sécurité',
      changePassword: 'Changer le mot de passe',
      biometrics: 'Biométrie',
      support: 'Support',
      helpCenter: "Centre d'aide",
      contactUs: 'Nous contacter',
      termsOfUse: "Conditions d'utilisation",
      profile: 'Profil',
      editProfileTitle: 'Modification du profil',
      editProfileSoon: 'Modification du profil bientôt disponible.',
      secureSession: 'Session sécurisée — Accès autorisé',
    },
    notifications: {
      new: 'Nouveau',
      unread: 'non lues',
      empty: 'Aucune notification',
      emptySubtitle: 'Vous serez notifié des nouvelles activités.',
    },
    teacherDashboard: {
      attendance: 'Présences',
      enterGrades: 'Saisir Notes',
      schedule: 'Emploi du temps',
      checkinMissing: 'Pointage non effectué',
      checkIn: 'Pointer',
      classes: 'Classes',
      students: 'Élèves',
      toGrade: 'À corriger',
      noClasses: 'Aucune classe',
      noClassesSubtitle: 'Aucune classe assignée pour le moment',
    },
    parentDashboard: {
      noChild: 'Aucun enfant rattaché',
      noChildSubtitle: "Contactez l'administration de l'établissement pour rattacher votre enfant à votre compte.",
      noClass: 'Classe non assignée',
      today: "Aujourd'hui",
      unpaid: 'Impayés',
      attendance: 'Présences',
      recentGrades: 'Dernières notes',
      upcomingAssignments: 'Prochains devoirs',
      upcomingEvents: 'Événements à venir',
    },
    staffCheckin: {
      locationRequired: 'Permission de localisation requise pour le pointage GPS.',
      arrivalSaved: 'Arrivée enregistrée avec succès',
      departureSaved: 'Départ enregistré',
      breakStarted: 'Pause commencée',
      breakEnded: 'Pause terminée',
      serviceDone: 'Service terminé',
      onBreak: 'En pause',
      notCheckedIn: 'Non pointé',
      myStatus: 'Mon statut',
      checkIn: 'Pointer mon arrivée',
      startBreak: 'Commencer la pause',
      resumeService: 'Reprendre le service',
      checkOut: 'Pointer mon départ',
      schedule: 'Horaires',
      gpsRadius: 'Rayon GPS',
      method: 'Méthode',
      recentHistory: 'Historique récent',
      noHistory: 'Aucun historique',
    },
    teacherClasses: {
      title: 'Mes Classes',
      classCount: 'classe',
      classCountPlural: 'classes',
    },
    teacherAttendance: {
      allPresent: 'Tous présents',
      reset: 'Réinitialiser',
      noStudents: 'Aucun élève',
      justified: 'Justifié',
      submitting: 'Envoi...',
      attention: 'Attention',
      markAtLeastOne: 'Veuillez marquer au moins un élève.',
      recordingFailed: "Échec de l'enregistrement.",
      attendanceRecorded: 'Présences enregistrées pour',
      students: 'élèves',
    },
    teacherGrades: {
      title: 'Saisie des Notes',
      subtitle: 'Enregistrez les performances académiques',
      coefficient: 'Coefficient',
      classAverage: 'MOYENNE',
      gradedStudents: 'Élèves notés',
      clear: 'Effacer',
      saving: 'Enregistrement...',
      validateGrades: 'Valider les notes',
      noAverages: 'Aucune moyenne calculée',
      ranking: 'Classement',
      gradeEntry: 'Saisie des notes',
      selectSubjectAndPeriod: 'Sélectionnez une matière et une période',
      noGradesEntered: 'Aucune note saisie',
      gradesSaved: 'notes enregistrées !',
      gradesValidated: 'notes validées !',
    },
    teacherSchedule: {
      noClassesForDay: 'Pas de cours prévu pour',
    },
    adminTeachers: {
      title: 'Enseignants',
      add: 'Ajouter',
      empty: 'Aucun enseignant trouvé',
      editTitle: 'Modifier enseignant',
      createTitle: 'Nouvel enseignant',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      subject: 'Matière',
      none: 'Aucune',
      firstNameRequired: 'Le prénom et le nom sont obligatoires',
      emailRequired: "L'email est obligatoire pour la création",
      deleteConfirm: "Supprimer l'enseignant",
      deleteError: 'Impossible de supprimer',
    },
    adminStudents: {
      title: 'Élèves',
      add: 'Ajouter',
      empty: 'Aucun élève trouvé',
      editTitle: 'Modifier élève',
      createTitle: 'Nouvel élève',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      emailOptional: 'Email (optionnel)',
      phone: 'Téléphone',
      matricule: 'Matricule',
      class: 'Classe',
      none: 'Aucune',
      required: 'Le prénom et le nom sont obligatoires',
      deleteConfirm: "Supprimer l'élève",
      deleteError: 'Impossible de supprimer',
    },
    adminClasses: {
      title: 'Classes',
      add: 'Ajouter',
      empty: 'Aucune classe trouvée',
      editTitle: 'Modifier classe',
      createTitle: 'Nouvelle classe',
      name: 'Nom',
      level: 'Niveau',
      capacity: 'Capacité',
      nameRequired: 'Le nom de la classe est obligatoire',
      deleteConfirm: 'Supprimer la classe',
      deleteError: 'Impossible de supprimer',
      placeholder: 'Ex: 6ème A',
      capacityPlaceholder: "Nombre d'élèves max",
    },
    visitorRegister: {
      title: 'Visiteurs',
      subtitle: 'visiteur(s) dans l\'établissement',
      formTitle: 'Enregistrer un visiteur',
      visitorName: 'Nom du visiteur *',
      phone: 'Téléphone',
      purpose: 'Motif de la visite *',
      personToVisit: 'Personne visitée *',
      personRole: 'Fonction (optionnel)',
      register: 'Enregistrer',
      empty: 'Aucun visiteur actuellement',
      registerSuccess: 'Visiteur enregistré avec succès',
      checkoutTitle: 'Confirmation',
      checkoutMessage: 'Enregistrer la sortie de ce visiteur ?',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      requiredError: 'Veuillez remplir tous les champs obligatoires',
    },
    qrBadge: {
      title: 'Mon Badge QR',
      teacher: 'Enseignant',
      student: 'Élève',
      staff: 'Personnel',
      unavailable: 'QR indisponible',
      retry: 'Réessayer',
      shareMessage: 'Mon badge QR EduCI: ',
      footer: 'EduCI - Éducation Côte d\'Ivoire',
      footerSub: 'Présentez ce badge au scanner',
    },
    teacherAssignments: {
      title: 'Mes Assignments',
      academicManagement: 'Gestion académique',
      create: 'Créer un assignment',
      noResults: 'Aucun résultat',
      empty: 'Aucun assignment. Créez-en un !',
      late: 'En retard',
      submissions: 'soumission(s)',
      editAssignment: "Modifier l'assignment",
      newAssignment: 'Nouvel assignment',
      titleField: 'Titre *',
      titlePlaceholder: "Titre de l'assignment",
      descriptionField: 'Description',
      descriptionPlaceholder: 'Description (optionnel)',
      classField: 'Classe *',
      subjectField: 'Matière',
      dueDateField: 'Date limite (AAAA-MM-JJ)',
      update: 'Mettre à jour',
      createBtn: 'Créer',
      titleRequired: 'Le titre est requis.',
      classRequired: 'Sélectionnez une classe.',
      notAuthenticated: 'Non authentifié',
      saveFailed: "Impossible d'enregistrer l'assignment.",
      confirmDelete: 'Voulez-vous vraiment supprimer cet assignment ?',
      deleteFailed: 'Suppression échouée.',
    },
  },
  en: {
    auth: {
      login: 'Login',
      email: 'Email',
      phone: 'Phone',
      matricule: 'Matricule',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign in',
      signingIn: 'Signing in...',
      createAccount: 'Create account',
      invitationCode: 'Invitation code',
      activateAccount: 'Activate my account',
      schoolCode: 'School code',
      secureAccess: 'Secure login. Invitation-only access.',
      backToLogin: 'Back to login',
      enterCredentials: 'Access your EduCI space',
    },
    errors: {
      required: 'Please fill in all fields.',
      invalidCredentials: 'Invalid credentials',
      accountLocked: 'Account locked',
      accountNotActivated: 'Account not activated. Contact your administrator.',
      serverError: 'Server error. Please try again later.',
      networkError: 'Connection error. Check your internet.',
      passwordMismatch: 'Passwords do not match.',
      passwordTooShort: 'Password must be at least 8 characters.',
    },
    success: {
      accountActivated: 'Account activated successfully!',
      schoolCreated: 'School created successfully!',
      passwordReset: 'A reset link has been sent.',
      attendanceSaved: 'Attendance saved successfully!',
      profileUpdated: 'Profile updated.',
    },
    common: {
      loading: 'Loading...',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      search: 'Search...',
      noData: 'No data',
      back: 'Back',
      next: 'Next',
      skip: 'Skip',
      getStarted: 'Get started',
      online: 'Online',
      submit: 'Submit',
      disconnect: 'Sign out',
      settings: 'Settings',
      profile: 'Profile',
      fullName: 'Full name',
      phone: 'Phone',
      error: 'Error',
      success: 'Success',
      role: 'Member',
      administrator: 'Administrator',
      teacher: 'Teacher',
      parent: 'Parent',
      student: 'Student',
      accountant: 'Accountant',
      secretary: 'Secretary',
      censeur: 'General Supervisor',
      supervisor: 'Supervisor',
      nameEmptyError: 'Name cannot be empty.',
      profileUpdateError: 'Unable to update profile.',
      permissionRequired: 'Permission required',
      galleryPermissionError: 'Gallery access is required to change your photo.',
      photoUpdated: 'Profile photo updated.',
      photoUploadError: 'Unable to upload photo.',
      course: 'Course',
      goodMorning: 'Good morning',
      goodAfternoon: 'Good afternoon',
      goodEvening: 'Good evening',
      seeAll: 'See all',
      dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    onboarding: {
      welcomeTitle: 'Welcome to',
      welcomeSubtitle: 'Connecting schools, teachers, students and parents in a single digital ecosystem.',
      trackTitle: 'Track Academic Success',
      trackSubtitle: 'Parents and teachers can monitor grades, attendance and performance in real time.',
      paymentsTitle: 'Secure &',
      paymentsHighlight: 'Safe Payments',
      paymentsSubtitle: 'Manage school fees easily with Orange Money, MTN MoMo or Wave.',
      authorizedBy: 'Approved by the Ministry of National Education',
      sampleGrade: 'Grade: 18/20',
      sampleSubject: 'Mathematics',
      sampleAttendance: '95% Attendance',
      sampleAttendancePeriod: 'This month',
      paymentLabel: 'PAYMENT',
      paymentSuccess: 'Successful',
    },
    home: {
      welcome: 'Welcome',
      myJourney: 'My Journey',
      level: 'Level 14: Scholar',
      progress: 'goals this month',
      average: 'Average',
      averageTitle: 'Overall Average',
      rank: 'Rank',
      attendance: 'Attendance',
      progression: 'Progression',
      quickActions: 'Quick actions',
      tasks: 'To-do this week',
      dueDate: 'Due date',
      aiAssistant: 'AI assistant available',
      nextCourse: 'Next course',
      recentMessages: 'Recent messages',
      noTask: 'No tasks',
      noTaskSubtitle: 'You have no tasks in progress',
      noAnnouncement: 'No announcements',
      noAnnouncementSubtitle: 'No announcements at the moment',
      noMessage: 'No messages',
      noMessageSubtitle: 'You have no messages yet',
      newBadge: 'New',
      unknown: 'Unknown',
      attendanceHistory: 'Attendance',
      present: 'Present',
      announcements: 'Announcements',
      documents: 'Documents',
      payments: 'Payments',
      student: 'Student',
    },
    grades: {
      title: 'Grades',
      subject: 'Subject',
      score: 'Score',
      date: 'Date',
      average: 'Average',
      reportCard: 'Report card',
      periods: 'Periods',
      noGradesSubtitle: 'Grades will be available soon',
      noBulletinsSubtitle: 'Report cards will be available soon',
    },
    payments: {
      title: 'Payments',
      payNow: 'Pay now',
      amount: 'Amount',
      method: 'Method',
      status: 'Status',
      paid: 'Paid',
      pending: 'Pending',
      overdue: 'Overdue',
      receipt: 'Receipt',
      invoices: 'Invoices',
      history: 'History',
      noPayments: 'No payments',
      noPaymentsSubtitle: 'No payments in progress',
    },
    messages: {
      title: 'Messages',
      allChats: 'All conversations',
      teachers: 'Teachers',
      admin: 'Admin',
      transport: 'Transport',
      online: 'Online',
      writeMessage: 'Write a message...',
      sendMessage: 'Send',
      communitySubtitle: 'Connect with your community',
      noConversations: 'No conversations',
      startChat: 'Start chatting',
    },
    transport: {
      title: 'School Transport',
      subtitle: 'Real-time bus tracking',
      bus: 'Bus',
      route: 'Route',
      delay: 'Delay',
      onTime: 'On time',
      liveTracking: 'GPS Tracking Active',
      activeBusesCount: 'buses in circulation',
      vehicles: 'Vehicles',
      passengers: 'Passengers',
      driver: 'Driver',
      eta: 'ETA',
      active: 'In circulation',
      enRoute: 'En route',
      maintenance: 'Maintenance',
      notifications: 'Approach notifications',
      notificationsSubtitle: 'Receive an alert when the bus approaches your stop.',
      noBuses: 'No buses available',
      noBusesSubtitle: 'No buses are currently available.',
    },
    marketplace: {
      title: 'Marketplace',
      search: 'Search resources...',
      all: 'All',
      course: 'Courses',
      quiz: 'Quiz',
      ebook: 'E-Books',
      tutoring: 'Tutoring',
      author: 'Author',
      purchases: 'purchases',
      confirmPurchase: 'Confirm purchase',
      purchaseConfirmMessage: 'Do you want to buy',
      buy: 'Buy',
      purchaseSuccess: 'Your purchase was completed successfully!',
      purchaseError: 'An error occurred during the purchase. Please try again.',
      noListings: 'No resources found',
      noListingsSubtitle: 'No resources match your search.',
    },
    courses: {
      title: 'My Courses',
      subjects: 'Subjects',
      today: 'Today',
      totalWeek: 'Total/week',
      noCoursesForDay: 'No courses',
      ongoing: 'Ongoing',
      room: 'Room',
    },
    ai: {
      title: 'EduCI AI',
      askQuestion: 'Ask a question...',
      send: 'Send',
      suggestions: 'Suggestions',
      resumeCourse: 'Summarize a course',
      explainExercise: 'Explain an exercise',
      generateQuiz: 'Generate a quiz',
      revisionTips: 'Revision tips',
      resetConfirm: 'Conversation reset. How can I help you?',
      errorMessage: 'Sorry, an error occurred. Check your internet connection and try again.',
      fallbackResponse: 'I could not process your request.',
    },
    examPrep: {
      title: 'Prepare for exams with EduCI AI',
      subtitle: 'Interactive quizzes, corrected past papers and AI assistant to succeed.',
      nationalExams: 'National Exams',
      continue: 'Continue',
      resources: 'Quick Resources',
      flashcards: 'Revision Cards',
      videos: 'Video Lessons',
      quizzes: 'Quick Quizzes',
      forum: 'Help Forum',
    },
    attendance_mark: {
      title: 'Mark attendance',
      selectClass: 'Select a class',
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      validate: 'Validate attendance',
      marked: 'marked',
      completed: 'Completed',
    },
    studentSchedule: {
      title: 'Schedule',
    },
    studentAssignments: {
      title: 'Assignments',
    },
    settings_screen: {
      disconnect: 'Sign out',
      disconnectConfirm: 'Do you want to sign out?',
      role: 'Role',
      email: 'Email',
      school: 'School',
      account: 'Account',
      editProfile: 'Edit profile',
      push: 'Push',
      notifications: 'Notifications',
      security: 'Security',
      changePassword: 'Change password',
      biometrics: 'Biometrics',
      support: 'Support',
      helpCenter: 'Help center',
      contactUs: 'Contact us',
      termsOfUse: 'Terms of use',
      profile: 'Profile',
      editProfileTitle: 'Edit profile',
      editProfileSoon: 'Profile editing coming soon.',
      secureSession: 'Secure session — Access authorized',
    },
    notifications: {
      new: 'New',
      unread: 'unread',
      empty: 'No notifications',
      emptySubtitle: 'You will be notified of new activities.',
    },
    teacherDashboard: {
      attendance: 'Attendance',
      enterGrades: 'Enter Grades',
      schedule: 'Schedule',
      checkinMissing: 'Check-in not done',
      checkIn: 'Check in',
      classes: 'Classes',
      students: 'Students',
      toGrade: 'To grade',
      noClasses: 'No classes',
      noClassesSubtitle: 'No classes assigned yet',
    },
    parentDashboard: {
      noChild: 'No child linked',
      noChildSubtitle: 'Contact the school administration to link your child to your account.',
      noClass: 'No class assigned',
      today: 'Today',
      unpaid: 'Unpaid',
      attendance: 'Attendance',
      recentGrades: 'Recent grades',
      upcomingAssignments: 'Upcoming assignments',
      upcomingEvents: 'Upcoming events',
    },
    staffCheckin: {
      locationRequired: 'Location permission required for GPS check-in.',
      arrivalSaved: 'Arrival saved successfully',
      departureSaved: 'Departure saved',
      breakStarted: 'Break started',
      breakEnded: 'Break ended',
      serviceDone: 'Service completed',
      onBreak: 'On break',
      notCheckedIn: 'Not checked in',
      myStatus: 'My status',
      checkIn: 'Check in',
      startBreak: 'Start break',
      resumeService: 'Resume service',
      checkOut: 'Check out',
      schedule: 'Schedule',
      gpsRadius: 'GPS radius',
      method: 'Method',
      recentHistory: 'Recent history',
      noHistory: 'No history',
    },
    teacherClasses: {
      title: 'My Classes',
      classCount: 'class',
      classCountPlural: 'classes',
    },
    teacherAttendance: {
      allPresent: 'All present',
      reset: 'Reset',
      noStudents: 'No students',
      justified: 'Justified',
      submitting: 'Sending...',
      attention: 'Attention',
      markAtLeastOne: 'Please mark at least one student.',
      recordingFailed: 'Recording failed.',
      attendanceRecorded: 'Attendance recorded for',
      students: 'students',
    },
    teacherGrades: {
      title: 'Grade Entry',
      subtitle: 'Record academic performance',
      coefficient: 'Coefficient',
      classAverage: 'AVERAGE',
      gradedStudents: 'Graded students',
      clear: 'Clear',
      saving: 'Saving...',
      validateGrades: 'Validate grades',
      noAverages: 'No averages calculated',
      ranking: 'Ranking',
      gradeEntry: 'Grade entry',
      selectSubjectAndPeriod: 'Select a subject and period',
      noGradesEntered: 'No grades entered',
      gradesSaved: 'grades saved!',
      gradesValidated: 'grades validated!',
    },
    teacherSchedule: {
      noClassesForDay: 'No classes scheduled for',
    },
    adminTeachers: {
      title: 'Teachers',
      add: 'Add',
      empty: 'No teachers found',
      editTitle: 'Edit teacher',
      createTitle: 'New teacher',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      subject: 'Subject',
      none: 'None',
      firstNameRequired: 'First and last name are required',
      emailRequired: 'Email is required for creation',
      deleteConfirm: 'Delete teacher',
      deleteError: 'Unable to delete',
    },
    adminStudents: {
      title: 'Students',
      add: 'Add',
      empty: 'No students found',
      editTitle: 'Edit student',
      createTitle: 'New student',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      emailOptional: 'Email (optional)',
      phone: 'Phone',
      matricule: 'Matricule',
      class: 'Class',
      none: 'None',
      required: 'First and last name are required',
      deleteConfirm: 'Delete student',
      deleteError: 'Unable to delete',
    },
    adminClasses: {
      title: 'Classes',
      add: 'Add',
      empty: 'No classes found',
      editTitle: 'Edit class',
      createTitle: 'New class',
      name: 'Name',
      level: 'Level',
      capacity: 'Capacity',
      nameRequired: 'Class name is required',
      deleteConfirm: 'Delete class',
      deleteError: 'Unable to delete',
      placeholder: 'e.g. 6th A',
      capacityPlaceholder: 'Max students',
    },
    visitorRegister: {
      title: 'Visitors',
      subtitle: 'visitor(s) on premises',
      formTitle: 'Register a visitor',
      visitorName: 'Visitor name *',
      phone: 'Phone',
      purpose: 'Visit purpose *',
      personToVisit: 'Person to visit *',
      personRole: 'Role (optional)',
      register: 'Register',
      empty: 'No visitors currently',
      registerSuccess: 'Visitor registered successfully',
      checkoutTitle: 'Confirmation',
      checkoutMessage: 'Record this visitor\'s departure?',
      cancel: 'Cancel',
      confirm: 'Confirm',
      requiredError: 'Please fill in all required fields',
    },
    qrBadge: {
      title: 'My QR Badge',
      teacher: 'Teacher',
      student: 'Student',
      staff: 'Staff',
      unavailable: 'QR unavailable',
      retry: 'Retry',
      shareMessage: 'My EduCI QR badge: ',
      footer: 'EduCI - Education Côte d\'Ivoire',
      footerSub: 'Show this badge at the scanner',
    },
    teacherAssignments: {
      title: 'My Assignments',
      academicManagement: 'Academic management',
      create: 'Create assignment',
      noResults: 'No results',
      empty: 'No assignments. Create one!',
      late: 'Late',
      submissions: 'submission(s)',
      editAssignment: 'Edit assignment',
      newAssignment: 'New assignment',
      titleField: 'Title *',
      titlePlaceholder: 'Assignment title',
      descriptionField: 'Description',
      descriptionPlaceholder: 'Description (optional)',
      classField: 'Class *',
      subjectField: 'Subject',
      dueDateField: 'Due date (YYYY-MM-DD)',
      update: 'Update',
      createBtn: 'Create',
      titleRequired: 'Title is required.',
      classRequired: 'Select a class.',
      notAuthenticated: 'Not authenticated',
      saveFailed: 'Unable to save assignment.',
      confirmDelete: 'Do you really want to delete this assignment?',
      deleteFailed: 'Deletion failed.',
    },
  },
};

const LANG_KEY = 'educi_lang';

function resolveKey(obj: any, key: string): string {
  const parts = key.split('.');
  let current = obj;
  for (const part of parts) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
    } else {
      return key;
    }
  }
  return typeof current === 'string' ? current : key;
}

const LangContext = createContext<LangContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (key: string) => resolveKey(translations.fr, key),
});

export const useLanguage = () => useContext(LangContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr');

  useEffect(() => {
    (async () => {
      try {
        const stored = await AsyncStorage.getItem(LANG_KEY);
        if (stored === 'fr' || stored === 'en') {
          setLangState(stored);
        }
      } catch {
        // default to 'fr'
      }
    })();
  }, []);

  const setLang = useCallback(async (l: Lang) => {
    setLangState(l);
    try {
      await AsyncStorage.setItem(LANG_KEY, l);
    } catch {
      // storage write failed, state still updated
    }
  }, []);

  const t = useCallback((key: string): string => {
    return resolveKey(translations[lang], key);
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}
