export const ASSESSMENT_ENGINE_CONFIG = {
  MAX_QUESTIONS_PER_EXAM: 200,
  TIME_LIMIT_MINUTES: 180,
  PASSING_SCORE: 60,
  MAX_ATTEMPTS: 3,
  AUTO_SUBMIT_ENABLED: true,
  PROCTORING_MODES: ['NONE', 'REMOTE', 'ONSITE', 'AI_PROCTORED'] as readonly string[],
  SECURE_BROWSER_LEVELS: ['STANDARD', 'ENHANCED', 'MAXIMUM'] as readonly string[],
  CHEATING_DETECTION_SENSITIVITY: 0.85,
  FACE_VERIFICATION_THRESHOLD: 0.92,
  SCREEN_MONITORING_INTERVAL: 30,
  MICROPHONE_SENSITIVITY: 0.7,
} as const;

export const QUESTION_BANK_CONFIG = {
  MAX_QUESTIONS_PER_CATEGORY: 5000,
  MAX_TAGS_PER_QUESTION: 10,
  DIFFICULTY_LEVELS: ['EASY', 'MEDIUM', 'HARD', 'EXPERT'] as readonly string[],
  BLOOM_TAXONOMY_LEVELS: ['REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE'] as readonly string[],
  VERSION_CONTROL_ENABLED: true,
  APPROVAL_WORKFLOW_STEPS: 3,
  STATISTICS_UPDATE_INTERVAL: 3600,
  DUPLICATE_SIMILARITY_THRESHOLD: 0.8,
  OCR_CONFIDENCE_THRESHOLD: 0.95,
  TRANSLATION_SUPPORTED_LANGUAGES: ['fr', 'en', 'ar', 'es', 'de', 'zh'] as readonly string[],
  BULK_EDIT_MAX_QUESTIONS: 100,
  IMPORT_MAX_FILE_SIZE_MB: 50,
} as const;

export const CERTIFICATION_CONFIG = {
  CERTIFICATE_TYPES: ['MODULE', 'SEMESTER', 'DEGREE', 'PROFESSIONAL', 'COMPETENCY'] as readonly string[],
  TEMPLATE_TYPES: ['STANDARD', 'HONORS', 'DISTINCTION', 'DIGITAL'] as readonly string[],
  CREDENTIAL_LEVELS: ['LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', 'LEVEL_6', 'LEVEL_7', 'LEVEL_8'] as readonly string[],
  BADGE_TYPES: ['SKILL', 'ACHIEVEMENT', 'PARTICIPATION', 'MASTERY'] as readonly string[],
  BLOCKCHAIN_NETWORKS: ['ETHEREUM', 'SOLANA', 'POLYGON', 'Hyperledger'] as readonly string[],
  QR_CODE_SIZE: 300,
  VERIFICATION_URL_EXPIRY: 86400,
  RENEWAL_REMINDER_DAYS: [90, 60, 30] as readonly number[],
  DIGITAL_SIGNATURE_ALGORITHM: 'RSA-SHA256',
  PDF_GENERATION_TIMEOUT: 30000,
} as const;

export const COMPETENCY_ASSESSMENT_CONFIG = {
  COMPETENCY_TEST_TYPES: ['DIRECT', 'INDIRECT', 'SELF_REPORT'] as readonly string[],
  PORTFOLIO_TYPES: ['ACADEMIC', 'PROFESSIONAL', 'RESEARCH', 'INTERNSHIP'] as readonly string[],
  ASSESSMENT_METHODS: ['EXAM', 'PROJECT', 'PRESENTATION', 'PRACTICAL', 'ORAL'] as readonly string[],
  SKILL_MATRIX_LEVELS: ['NOVICE', 'BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT'] as readonly string[],
  ASSESSMENT_FREQUENCIES: ['WEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMESTER', 'ANNUAL'] as readonly string[],
  RUBRIC_MAX_CRITERIA: 20,
  PEER_ASSESSMENT_ANONYMOUS: true,
  SELF_REFLECTION_REQUIRED: true,
} as const;

export const NATIONAL_EXAM_CONFIG = {
  EXAM_TYPES: ['BAC1', 'BAC2', 'BAC3', 'LICENCE', 'MASTER', 'DOCTORAT'] as readonly string[],
  CENTER_STATUSES: ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'UNDER_REVIEW'] as readonly string[],
  REGISTRATION_DEADLINES: { EARLY: 90, STANDARD: 60, LATE: 30 } as const,
  ANONYMOUS_NUMBER_FORMAT: 'AN-{YEAR}-{CENTER}-{SEQ:6}',
  DOUBLE_MARKING_TOLERANCE: 2,
  MODERATION_SAMPLE_SIZE: 0.1,
  APPEAL_DEADLINE_DAYS: 30,
  RESULTS_PUBLICATION_DELAY: 45,
  RANKING_CALCULATION_METHOD: 'WEIGHTED_AVERAGE',
  SECURE_PRINT_QA_CHECKS: ['BARCODE', 'WATERMARK', 'SERIAL_NUMBER', 'MICROPRINT'] as readonly string[],
} as const;

export const ACCREDITATION_CONFIG = {
  ACCREDITATION_TYPES: ['INSTITUTIONAL', 'PROGRAM', 'COURSE', 'COMPETENCY'] as readonly string[],
  COMPLIANCE_STATUSES: ['COMPLIANT', 'PARTIAL', 'NON_COMPLIANT', 'UNDER_REVIEW'] as readonly string[],
  AUDIT_FREQUENCIES: ['ANNUAL', 'BIENNIAL', 'TRIENNIAL'] as readonly string[],
  EVIDENCE_REQUIRED_PER_STANDARD: 5,
  RENEWAL_ADVANCE_MONTHS: 12,
  CORRECTIVE_ACTION_DEADLINE_DAYS: 90,
  REPORT_GENERATION_TIMEOUT: 60000,
} as const;

export const INTEGRITY_CONFIG = {
  PLAGIARISM_THRESHOLD: 0.2,
  AI_DETECTION_THRESHOLD: 0.85,
  IDENTITY_VERIFICATION_METHODS: ['FACE_RECOGNITION', 'ID_DOCUMENT', 'BIOMETRIC', 'VOICE_PATTERN'] as readonly string[],
  BEHAVIOR_ANALYSIS_SENSITIVITY: 0.75,
  FRAUD_CONFIDENCE_THRESHOLD: 0.9,
  REPORT_RETENTION_DAYS: 365,
  CITATION_FORMATS: ['APA', 'MLA', 'CHICAGO', 'IEEE', 'HARVARD'] as readonly string[],
  SIMILARITY_ALGORITHM_VERSION: '3.2',
} as const;

export const PORTFOLIO_CONFIG = {
  PORTFOLIO_TYPES: ['ACADEMIC', 'PROFESSIONAL', 'COMPETENCY', 'PROJECT', 'RESEARCH'] as readonly string[],
  VISIBILITY_OPTIONS: ['PRIVATE', 'SHARED', 'PUBLIC', 'MENTOR_ONLY'] as readonly string[],
  MAX_ITEMS_PER_PORTFOLIO: 500,
  SUPPORTED_FILE_TYPES: ['PDF', 'DOCX', 'PPTX', 'MP4', 'MP3', 'JPG', 'PNG', 'GIF', 'ZIP'] as readonly string[],
  MAX_FILE_SIZE_MB: 100,
  EXPORT_FORMATS: ['PDF', 'ZIP', 'HTML', 'JSON'] as readonly string[],
  PUBLIC_URL_EXPIRY: 2592000,
  SHARING_PERMISSION_LEVELS: ['VIEW', 'COMMENT', 'EDIT', 'ADMIN'] as readonly string[],
} as const;

export const RESEARCH_CONFIG = {
  PROJECT_STATUSES: ['DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'PUBLISHED'] as readonly string[],
  PUBLICATION_TYPES: ['JOURNAL', 'CONFERENCE', 'BOOK_CHAPTER', 'REPORT', 'PATENT', 'THESIS'] as readonly string[],
  GRANT_STATUSES: ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ACTIVE', 'CLOSED'] as readonly string[],
  COLLABORATION_TYPES: ['INTERNAL', 'NATIONAL', 'INTERNATIONAL', 'INDUSTRY'] as readonly string[],
  INNOVATION_LAB_STATUSES: ['PLANNING', 'SETUP', 'ACTIVE', 'EXPANSION', 'CLOSURE'] as readonly string[],
  REPOSITORY_UPDATE_INTERVAL: 3600,
  KPI_CALCULATION_PERIOD: 86400,
  PATENT_TRACKING_ENABLED: true,
} as const;

export const INTERNATIONAL_CONFIG = {
  EXAM_TYPES: ['LOCAL', 'INTERNATIONAL', 'JOINT_DEGREE', 'EXCHANGE'] as readonly string[],
  CREDIT_SYSTEMS: ['ECTS', 'US_CREDITS', 'CREDIT_HOURS', 'MODULE_POINTS'] as readonly string[],
  RECOGNITION_STATUSES: ['PENDING', 'RECOGNIZED', 'CONDITIONAL', 'REJECTED', 'EXPIRED'] as readonly string[],
  TRANSFER_EVALUATION_METHODS: ['EQUIVALENCY', 'ADAPTATION', 'COMPLEMENTARY', 'FULL_RECOGNITION'] as readonly string[],
  EQUIVALENCY_TABLE_VERSION: '2.1',
  ECTS_CONVERSION_FACTOR: 1.0,
  COUNTRY_SPECIFIC_RULES: ['FRANCE', 'GERMANY', 'SPAIN', 'UK', 'USA', 'JAPAN', 'CHINA'] as readonly string[],
} as const;

export const AI_ASSESSMENT_CONFIG = {
  FEEDBACK_TYPES: ['AUTO', 'SEMI_AUTO', 'MANUAL', 'HYBRID'] as readonly string[],
  PREDICTION_MODELS: ['LINEAR', 'DECISION_TREE', 'NEURAL_NETWORK', 'ENSEMBLE'] as readonly string[],
  MODERATION_TYPES: ['AI_FIRST', 'HUMAN_FIRST', 'PARALLEL', 'AI_RECOMMENDATION'] as readonly string[],
  INVIGILATOR_ACTIONS: ['ALERT', 'WARNING', 'PAUSE_EXAM', 'TERMINATE_EXAM', 'FLAG_FOR_REVIEW'] as readonly string[],
  WEAKNESS_DETECTION_ALGORITHM: 'COLLABORATIVE_FILTERING',
  DIFFICULTY_ADJUSTMENT_RATE: 0.15,
  RISK_CALCULATION_WEIGHTS: {
    BEHAVIOR: 0.3,
    PERFORMANCE: 0.3,
    IDENTITY: 0.2,
    TIMING: 0.2,
  } as const,
} as const;

export const GRADING_CONFIG = {
  GRADE_SCALES: ['NUMERIC_0_20', 'LETTER_A_F', 'PERCENTAGE', 'COMPETENCY_BASED', 'PASS_FAIL'] as readonly string[],
  GRADING_METHODS: ['ABSOLUTE', 'RELATIVE', 'CURVED', 'MASTERY', 'RUBRIC_BASED'] as readonly string[],
  RUBRIC_LEVELS: ['EXCELLENT', 'GOOD', 'SATISFACTORY', 'NEEDS_IMPROVEMENT', 'UNSATISFACTORY'] as readonly string[],
  AUTO_GRADING_CONFIDENCE_THRESHOLD: 0.9,
  MANUAL_REVIEW_THRESHOLD: 0.7,
  GRADE_APPEAL_DEADLINE_DAYS: 15,
  BULK_GRADING_MAX_BATCH_SIZE: 500,
} as const;

export const EXAM_SESSION_CONFIG = {
  SESSION_TIMEOUT_MINUTES: 30,
  MAX_CONCURRENT_SESSIONS: 5,
  HEARTBEAT_INTERVAL_SECONDS: 30,
  AUTO_SAVE_INTERVAL_SECONDS: 60,
  RECONNECTION_GRACE_PERIOD_SECONDS: 120,
  MAX_TAB_SWITCHES: 3,
  SCREENSHOT_CAPTURE_INTERVAL: 300,
} as const;

export const PROCTORING_CONFIG = {
  PROCTORING_MODES: ['LIVE', 'RECORDED', 'AI_ONLY', 'HYBRID'] as readonly string[],
  FACE_DETECTION_MODEL: 'YOLO_V8',
  EYE_TRACKING_SENSITIVITY: 0.8,
  AUDIO_MONITORING_ENABLED: true,
  SCREEN_RECORDING_QUALITY: '720P',
  ALERT_ESCALATION_TIME_SECONDS: 30,
  PROCTOR_QUEUE_MAX_SIZE: 50,
} as const;

export const CORRECTION_CONFIG = {
  DOUBLE_MARKING_TOLERANCE_PERCENT: 10,
  MODERATION_SAMPLE_RATE: 0.15,
  MARKER_WORKLOAD_MAX: 100,
  DEADLINE_EXTENSIONS_ALLOWED: 2,
  COMMENT_TEMPLATES: ['EXCELLENT_WORK', 'GOOD_EFFORT', 'NEEDS_IMPROVEMENT', 'REQUIRES_RESUBMISSION'] as readonly string[],
  BATCH_CORRECTION_ENABLED: true,
} as const;

export const RESULTS_CONFIG = {
  PUBLICATION_METHODS: ['INSTANT', 'BATCH', 'SCHEDULED', 'MANUAL_RELEASE'] as readonly string[],
  RANKING_ALGORITHMS: ['ABSOLUTE', 'PERCENTILE', 'WEIGHTED', 'CLASSIFICATION'] as readonly string[],
  STATISTICS_CALCULATION_PERIOD: 'DAILY',
  ANALYTICS_RETENTION_MONTHS: 60,
  NOTIFICATION_METHODS: ['EMAIL', 'SMS', 'PUSH', 'IN_APP'] as readonly string[],
  DOWNLOAD_FORMATS: ['PDF', 'CSV', 'JSON', 'XML'] as readonly string[],
} as const;

export const DOCUMENT_CONFIG = {
  PDF_GENERATION_ENGINE: 'PUPPETEER',
  IMAGE_PROCESSING_MAX_SIZE: 10485760,
  VIDEO_PROCESSING_MAX_DURATION: 3600,
  AUDIO_TRANSCRIPTION_ENABLED: true,
  OCR_ENGINE: 'TESSERACT',
  FILE_STORAGE_PROVIDER: 'AWS_S3',
  CDN_ENABLED: true,
} as const;

export const SECURITY_CONFIG = {
  ENCRYPTION_ALGORITHM: 'AES-256-GCM',
  DATA_RETENTION_YEARS: 10,
  AUDIT_LOG_RETENTION: 2555,
  IP_WHITELIST_ENABLED: false,
  RATE_LIMIT_PER_MINUTE: 100,
  SESSION_EXPIRY_HOURS: 8,
  MFA_REQUIRED_FOR_ADMIN: true,
} as const;

export const OFFLINE_CONFIG = {
  SYNC_INTERVAL_MINUTES: 5,
  MAX_OFFLINE_ENTRIES: 10000,
  CONFLICT_RESOLUTION_STRATEGY: 'SERVER_WINS',
  COMPRESSION_ENABLED: true,
  INCREMENTAL_SYNC_ENABLED: true,
  OFFLINE_STORAGE_LIMIT_MB: 500,
} as const;

export const NOTIFICATION_CONFIG = {
  EMAIL_TEMPLATES: [
    'EXAM_SCHEDULED',
    'RESULTS_READY',
    'CERTIFICATE_ISSUED',
    'DEADLINE_REMINDER',
    'SYSTEM_MAINTENANCE',
    'SECURITY_ALERT',
  ] as readonly string[],
  SMS_ENABLED: true,
  PUSH_NOTIFICATIONS: true,
  IN_APP_NOTIFICATIONS: true,
  NOTIFICATION_BATCH_SIZE: 100,
  DELIVERY_RETRY_ATTEMPTS: 3,
  QUIET_HOURS_ENABLED: true,
} as const;

export const REPORT_CONFIG = {
  REPORT_TYPES: ['ACADEMIC', 'FINANCIAL', 'ATTENDANCE', 'PERFORMANCE', 'COMPLIANCE'] as readonly string[],
  SCHEDULED_REPORTS: ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL'] as readonly string[],
  REPORT_RETENTION_DAYS: 365,
  EXPORT_FORMATS: ['PDF', 'EXCEL', 'CSV', 'JSON'] as readonly string[],
  MAX_REPORT_ROWS: 100000,
  CHART_TYPES: ['BAR', 'LINE', 'PIE', 'SCATTER', 'HEATMAP'] as readonly string[],
  PDF_WATERMARK_ENABLED: true,
} as const;

export const ANALYTICS_CONFIG = {
  DASHBOARD_REFRESH_INTERVAL: 300,
  METRIC_AGGREGATION_PERIOD: 3600,
  REAL_TIME_ENABLED: true,
  HISTORICAL_DATA_RETENTION_YEARS: 5,
  COMPARISON_BASELINE_PERIOD: 'SEMESTER',
  PREDICTION_HORIZON_DAYS: 90,
} as const;

export const API_CONFIG = {
  RATE_LIMIT_PER_MINUTE: 60,
  MAX_PAGE_SIZE: 200,
  DEFAULT_PAGE_SIZE: 20,
  SORT_ALLOWED_FIELDS: ['createdAt', 'updatedAt', 'name', 'status', 'score'] as readonly string[],
  FILTER_OPERATORS: ['eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'in', 'like'] as readonly string[],
  CORS_ORIGINS: ['http://localhost:3000', 'http://localhost:5173'] as readonly string[],
  API_VERSION_PREFIX: '/api/v1',
} as const;

export const MOBILE_CONFIG = {
  OFFLINE_SYNC_ENABLED: true,
  PUSH_NOTIFICATION_ENABLED: true,
  BIOMETRIC_AUTH_ENABLED: true,
  CAMERA_CAPTURE_ENABLED: true,
  QR_SCANNER_ENABLED: true,
  FILE_DOWNLOAD_MAX_SIZE_MB: 50,
} as const;
