import { z } from 'zod';

const schoolId = z.string().uuid();

// ── Research Project ─────────────────────────────────────────────────────

export const researchProjectCreateSchema = z.object({
  school_id: schoolId,
  project_name: z.string().min(1).max(300),
  description: z.string().max(5000).optional(),
  research_area: z.string().min(1).max(200),
  research_type: z.enum(['basic', 'applied', 'experimental', 'theoretical', 'mixed_methods']),
  methodology: z.string().max(2000).optional(),
  principal_investigator_id: z.string().uuid(),
  co_investigators: z.array(z.string().uuid()).optional(),
  team_members: z.array(z.string().uuid()).optional(),
  start_date: z.string().datetime(),
  end_date: z.string().datetime().optional(),
  budget: z.number().min(0).optional(),
  funding_source: z.string().max(200).optional(),
  status: z.enum(['proposal', 'approved', 'in_progress', 'completed', 'on_hold', 'cancelled']).optional(),
  ethics_approval_required: z.boolean().optional(),
  ethics_approval_status: z.enum(['not_required', 'pending', 'approved', 'denied']).optional(),
  keywords: z.array(z.string().max(100)).optional(),
  notes: z.string().max(5000).optional(),
});

export const researchProjectUpdateSchema = z.object({
  school_id: schoolId,
  project_name: z.string().min(1).max(300).optional(),
  description: z.string().max(5000).optional(),
  research_area: z.string().min(1).max(200).optional(),
  research_type: z.enum(['basic', 'applied', 'experimental', 'theoretical', 'mixed_methods']).optional(),
  methodology: z.string().max(2000).optional(),
  principal_investigator_id: z.string().uuid().optional(),
  co_investigators: z.array(z.string().uuid()).optional(),
  team_members: z.array(z.string().uuid()).optional(),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  budget: z.number().min(0).optional(),
  funding_source: z.string().max(200).optional(),
  status: z.enum(['proposal', 'approved', 'in_progress', 'completed', 'on_hold', 'cancelled']).optional(),
  ethics_approval_required: z.boolean().optional(),
  ethics_approval_status: z.enum(['not_required', 'pending', 'approved', 'denied']).optional(),
  keywords: z.array(z.string().max(100)).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Innovation Lab ───────────────────────────────────────────────────────

export const innovationLabCreateSchema = z.object({
  school_id: schoolId,
  lab_name: z.string().min(1).max(300),
  description: z.string().max(5000).optional(),
  lab_type: z.enum(['maker_space', 'research_lab', 'incubator', 'fab_lab', 'media_lab', 'ai_lab']),
  location: z.string().max(300).optional(),
  capacity: z.number().int().min(1).optional(),
  equipment: z.array(z.string().max(200)).optional(),
  software_tools: z.array(z.string().max(200)).optional(),
  manager_id: z.string().uuid().optional(),
  opening_hours: z.string().max(500).optional(),
  booking_required: z.boolean().optional(),
  access_level: z.enum(['open', 'restricted', 'invite_only']).optional(),
  status: z.enum(['active', 'inactive', 'under_maintenance', 'planned']).optional(),
  established_date: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

export const innovationLabUpdateSchema = z.object({
  school_id: schoolId,
  lab_name: z.string().min(1).max(300).optional(),
  description: z.string().max(5000).optional(),
  lab_type: z.enum(['maker_space', 'research_lab', 'incubator', 'fab_lab', 'media_lab', 'ai_lab']).optional(),
  location: z.string().max(300).optional(),
  capacity: z.number().int().min(1).optional(),
  equipment: z.array(z.string().max(200)).optional(),
  software_tools: z.array(z.string().max(200)).optional(),
  manager_id: z.string().uuid().optional(),
  opening_hours: z.string().max(500).optional(),
  booking_required: z.boolean().optional(),
  access_level: z.enum(['open', 'restricted', 'invite_only']).optional(),
  status: z.enum(['active', 'inactive', 'under_maintenance', 'planned']).optional(),
  established_date: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

// ── Publication ──────────────────────────────────────────────────────────

export const publicationCreateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  title: z.string().min(1).max(500),
  abstract: z.string().max(5000).optional(),
  publication_type: z.enum(['journal_article', 'conference_paper', 'book_chapter', 'book', 'patent', 'report', 'preprint']),
  authors: z.array(z.string().max(200)).min(1),
  journal_name: z.string().max(300).optional(),
  conference_name: z.string().max(300).optional(),
  volume: z.string().max(50).optional(),
  issue: z.string().max(50).optional(),
  pages: z.string().max(50).optional(),
  doi: z.string().max(100).optional(),
  isbn: z.string().max(20).optional(),
  issn: z.string().max(20).optional(),
  publication_date: z.string().datetime().optional(),
  peer_reviewed: z.boolean().optional(),
  impact_factor: z.number().min(0).optional(),
  citations_count: z.number().int().min(0).optional(),
  open_access: z.boolean().optional(),
  pdf_url: z.string().url().optional(),
  external_url: z.string().url().optional(),
  status: z.enum(['draft', 'submitted', 'under_review', 'revision_required', 'accepted', 'published', 'rejected']).optional(),
  notes: z.string().max(5000).optional(),
});

export const publicationUpdateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  title: z.string().min(1).max(500).optional(),
  abstract: z.string().max(5000).optional(),
  publication_type: z.enum(['journal_article', 'conference_paper', 'book_chapter', 'book', 'patent', 'report', 'preprint']).optional(),
  authors: z.array(z.string().max(200)).optional(),
  journal_name: z.string().max(300).optional(),
  conference_name: z.string().max(300).optional(),
  volume: z.string().max(50).optional(),
  issue: z.string().max(50).optional(),
  pages: z.string().max(50).optional(),
  doi: z.string().max(100).optional(),
  isbn: z.string().max(20).optional(),
  issn: z.string().max(20).optional(),
  publication_date: z.string().datetime().optional(),
  peer_reviewed: z.boolean().optional(),
  impact_factor: z.number().min(0).optional(),
  citations_count: z.number().int().min(0).optional(),
  open_access: z.boolean().optional(),
  pdf_url: z.string().url().optional(),
  external_url: z.string().url().optional(),
  status: z.enum(['draft', 'submitted', 'under_review', 'revision_required', 'accepted', 'published', 'rejected']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Research Grant ───────────────────────────────────────────────────────

export const researchGrantCreateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  grant_name: z.string().min(1).max(300),
  funding_agency: z.string().min(1).max(300),
  grant_program: z.string().max(200).optional(),
  amount_requested: z.number().min(0),
  amount_approved: z.number().min(0).optional(),
  currency: z.string().length(3).optional(),
  application_date: z.string().datetime(),
  decision_date: z.string().datetime().optional(),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  grant_type: z.enum(['federal', 'state', 'private', 'industry', 'international', 'internal']),
  status: z.enum(['draft', 'submitted', 'under_review', 'approved', 'declined', 'active', 'completed', 'terminated']).optional(),
  principal_investigator_id: z.string().uuid(),
  grant_number: z.string().max(100).optional(),
  deliverables: z.array(z.string().max(500)).optional(),
  notes: z.string().max(5000).optional(),
});

export const researchGrantUpdateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  grant_name: z.string().min(1).max(300).optional(),
  funding_agency: z.string().min(1).max(300).optional(),
  grant_program: z.string().max(200).optional(),
  amount_requested: z.number().min(0).optional(),
  amount_approved: z.number().min(0).optional(),
  currency: z.string().length(3).optional(),
  application_date: z.string().datetime().optional(),
  decision_date: z.string().datetime().optional(),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  grant_type: z.enum(['federal', 'state', 'private', 'industry', 'international', 'internal']).optional(),
  status: z.enum(['draft', 'submitted', 'under_review', 'approved', 'declined', 'active', 'completed', 'terminated']).optional(),
  principal_investigator_id: z.string().uuid().optional(),
  grant_number: z.string().max(100).optional(),
  deliverables: z.array(z.string().max(500)).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Research Team ────────────────────────────────────────────────────────

export const researchTeamCreateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid(),
  team_name: z.string().min(1).max(200),
  members: z.array(z.object({
    user_id: z.string().uuid(),
    role: z.enum(['principal_investigator', 'co_investigator', 'researcher', 'assistant', 'student', 'advisor']),
    contribution: z.string().max(500).optional(),
    start_date: z.string().datetime().optional(),
    end_date: z.string().datetime().optional(),
    allocation_percentage: z.number().min(0).max(100).optional(),
  })).min(1),
  lead_researcher_id: z.string().uuid(),
  total_funding_allocated: z.number().min(0).optional(),
  status: z.enum(['forming', 'active', 'dissolved', 'on_hold']).optional(),
  notes: z.string().max(5000).optional(),
});

export const researchTeamUpdateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  team_name: z.string().min(1).max(200).optional(),
  members: z.array(z.object({
    user_id: z.string().uuid(),
    role: z.enum(['principal_investigator', 'co_investigator', 'researcher', 'assistant', 'student', 'advisor']),
    contribution: z.string().max(500).optional(),
    start_date: z.string().datetime().optional(),
    end_date: z.string().datetime().optional(),
    allocation_percentage: z.number().min(0).max(100).optional(),
  })).optional(),
  lead_researcher_id: z.string().uuid().optional(),
  total_funding_allocated: z.number().min(0).optional(),
  status: z.enum(['forming', 'active', 'dissolved', 'on_hold']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Research Analytics ───────────────────────────────────────────────────

export const researchAnalyticsCreateSchema = z.object({
  school_id: schoolId,
  analytics_type: z.enum(['institutional', 'departmental', 'project', 'individual']),
  subject_id: z.string().uuid().optional(),
  period_start: z.string().datetime(),
  period_end: z.string().datetime(),
  total_projects: z.number().int().min(0).optional(),
  active_projects: z.number().int().min(0).optional(),
  completed_projects: z.number().int().min(0).optional(),
  total_publications: z.number().int().min(0).optional(),
  total_citations: z.number().int().min(0).optional(),
  total_grants: z.number().int().min(0).optional(),
  total_funding: z.number().min(0).optional(),
  h_index: z.number().int().min(0).optional(),
  avg_impact_factor: z.number().min(0).optional(),
  collaboration_score: z.number().min(0).max(100).optional(),
  innovation_score: z.number().min(0).max(100).optional(),
  breakdown_by_area: z.record(z.number().int().min(0)).optional(),
  breakdown_by_type: z.record(z.number().int().min(0)).optional(),
  generated_at: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

export const researchAnalyticsUpdateSchema = z.object({
  school_id: schoolId,
  analytics_type: z.enum(['institutional', 'departmental', 'project', 'individual']).optional(),
  subject_id: z.string().uuid().optional(),
  period_start: z.string().datetime().optional(),
  period_end: z.string().datetime().optional(),
  total_projects: z.number().int().min(0).optional(),
  active_projects: z.number().int().min(0).optional(),
  completed_projects: z.number().int().min(0).optional(),
  total_publications: z.number().int().min(0).optional(),
  total_citations: z.number().int().min(0).optional(),
  total_grants: z.number().int().min(0).optional(),
  total_funding: z.number().min(0).optional(),
  h_index: z.number().int().min(0).optional(),
  avg_impact_factor: z.number().min(0).optional(),
  collaboration_score: z.number().min(0).max(100).optional(),
  innovation_score: z.number().min(0).max(100).optional(),
  breakdown_by_area: z.record(z.number().int().min(0)).optional(),
  breakdown_by_type: z.record(z.number().int().min(0)).optional(),
  generated_at: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

// ── Research KPI ─────────────────────────────────────────────────────────

export const researchKPICreateSchema = z.object({
  school_id: schoolId,
  kpi_name: z.string().min(1).max(200),
  kpi_category: z.enum(['productivity', 'impact', 'collaboration', 'innovation', 'funding']),
  target_value: z.number(),
  current_value: z.number().optional(),
  unit: z.string().max(50).optional(),
  period: z.string().max(50),
  department_id: z.string().uuid().optional(),
  benchmark_value: z.number().optional(),
  weight: z.number().min(0).max(1).optional(),
  target_date: z.string().datetime().optional(),
  status: z.enum(['on_track', 'at_risk', 'behind', 'achieved', 'exceeded']).optional(),
  trend: z.enum(['improving', 'stable', 'declining']).optional(),
  notes: z.string().max(5000).optional(),
});

export const researchKPIUpdateSchema = z.object({
  school_id: schoolId,
  kpi_name: z.string().min(1).max(200).optional(),
  kpi_category: z.enum(['productivity', 'impact', 'collaboration', 'innovation', 'funding']).optional(),
  target_value: z.number().optional(),
  current_value: z.number().optional(),
  unit: z.string().max(50).optional(),
  period: z.string().max(50).optional(),
  department_id: z.string().uuid().optional(),
  benchmark_value: z.number().optional(),
  weight: z.number().min(0).max(1).optional(),
  target_date: z.string().datetime().optional(),
  status: z.enum(['on_track', 'at_risk', 'behind', 'achieved', 'exceeded']).optional(),
  trend: z.enum(['improving', 'stable', 'declining']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Patent Tracking ──────────────────────────────────────────────────────

export const patentTrackingCreateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  patent_title: z.string().min(1).max(500),
  patent_number: z.string().max(100).optional(),
  application_number: z.string().max(100).optional(),
  filing_date: z.string().datetime(),
  grant_date: z.string().datetime().optional(),
  expiry_date: z.string().datetime().optional(),
  patent_type: z.enum(['utility', 'design', 'provisional', 'continuation', 'international']),
  status: z.enum(['filed', 'pending', 'granted', 'expired', 'abandoned', 'licensed']),
  inventors: z.array(z.string().max(200)).min(1),
  assignee: z.string().max(300).optional(),
  filing_office: z.string().max(100).optional(),
  classification: z.string().max(100).optional(),
  abstract: z.string().max(3000).optional(),
  licensing_status: z.enum(['none', 'exclusive', 'non_exclusive', 'sole']).optional(),
  revenue_generated: z.number().min(0).optional(),
  notes: z.string().max(5000).optional(),
});

export const patentTrackingUpdateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  patent_title: z.string().min(1).max(500).optional(),
  patent_number: z.string().max(100).optional(),
  application_number: z.string().max(100).optional(),
  filing_date: z.string().datetime().optional(),
  grant_date: z.string().datetime().optional(),
  expiry_date: z.string().datetime().optional(),
  patent_type: z.enum(['utility', 'design', 'provisional', 'continuation', 'international']).optional(),
  status: z.enum(['filed', 'pending', 'granted', 'expired', 'abandoned', 'licensed']).optional(),
  inventors: z.array(z.string().max(200)).optional(),
  assignee: z.string().max(300).optional(),
  filing_office: z.string().max(100).optional(),
  classification: z.string().max(100).optional(),
  abstract: z.string().max(3000).optional(),
  licensing_status: z.enum(['none', 'exclusive', 'non_exclusive', 'sole']).optional(),
  revenue_generated: z.number().min(0).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Research Collaboration ───────────────────────────────────────────────

export const researchCollaborationCreateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid(),
  collaboration_name: z.string().min(1).max(300),
  partner_institution: z.string().min(1).max(300),
  partner_country: z.string().max(100).optional(),
  partner_contact: z.string().max(200).optional(),
  collaboration_type: z.enum(['joint_research', 'data_sharing', 'student_exchange', 'visiting_scholar', 'consortium']),
  start_date: z.string().datetime(),
  end_date: z.string().datetime().optional(),
  shared_resources: z.array(z.string().max(200)).optional(),
  ip_agreement: z.boolean().optional(),
  funding_split: z.record(z.number().min(0)).optional(),
  lead_institution: z.string().max(300).optional(),
  status: z.enum(['proposed', 'negotiating', 'active', 'completed', 'terminated']).optional(),
  agreements_url: z.string().url().optional(),
  notes: z.string().max(5000).optional(),
});

export const researchCollaborationUpdateSchema = z.object({
  school_id: schoolId,
  project_id: z.string().uuid().optional(),
  collaboration_name: z.string().min(1).max(300).optional(),
  partner_institution: z.string().min(1).max(300).optional(),
  partner_country: z.string().max(100).optional(),
  partner_contact: z.string().max(200).optional(),
  collaboration_type: z.enum(['joint_research', 'data_sharing', 'student_exchange', 'visiting_scholar', 'consortium']).optional(),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  shared_resources: z.array(z.string().max(200)).optional(),
  ip_agreement: z.boolean().optional(),
  funding_split: z.record(z.number().min(0)).optional(),
  lead_institution: z.string().max(300).optional(),
  status: z.enum(['proposed', 'negotiating', 'active', 'completed', 'terminated']).optional(),
  agreements_url: z.string().url().optional(),
  notes: z.string().max(5000).optional(),
});

// ── International Exam ───────────────────────────────────────────────────

export const internationalExamCreateSchema = z.object({
  school_id: schoolId,
  exam_name: z.string().min(1).max(300),
  exam_code: z.string().min(1).max(50),
  exam_body: z.string().min(1).max(300),
  exam_level: z.enum(['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'beginner', 'intermediate', 'advanced']),
  subject_area: z.string().max(200).optional(),
  language: z.string().min(2).max(50),
  exam_date: z.string().datetime(),
  registration_deadline: z.string().datetime().optional(),
  duration_minutes: z.number().int().min(1).max(600),
  max_score: z.number().int().min(1),
  passing_score: z.number().int().min(0),
  fee_amount: z.number().min(0).optional(),
  fee_currency: z.string().length(3).optional(),
  eligibility_criteria: z.array(z.string().max(300)).optional(),
  exam_format: z.enum(['paper', 'computer', 'online', 'hybrid']).optional(),
  max_candidates: z.number().int().min(1).optional(),
  registered_count: z.number().int().min(0).optional(),
  status: z.enum(['planned', 'registration_open', 'registration_closed', 'in_progress', 'completed', 'cancelled']).optional(),
  notes: z.string().max(5000).optional(),
});

export const internationalExamUpdateSchema = z.object({
  school_id: schoolId,
  exam_name: z.string().min(1).max(300).optional(),
  exam_code: z.string().min(1).max(50).optional(),
  exam_body: z.string().min(1).max(300).optional(),
  exam_level: z.enum(['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'beginner', 'intermediate', 'advanced']).optional(),
  subject_area: z.string().max(200).optional(),
  language: z.string().min(2).max(50).optional(),
  exam_date: z.string().datetime().optional(),
  registration_deadline: z.string().datetime().optional(),
  duration_minutes: z.number().int().min(1).max(600).optional(),
  max_score: z.number().int().min(1).optional(),
  passing_score: z.number().int().min(0).optional(),
  fee_amount: z.number().min(0).optional(),
  fee_currency: z.string().length(3).optional(),
  eligibility_criteria: z.array(z.string().max(300)).optional(),
  exam_format: z.enum(['paper', 'computer', 'online', 'hybrid']).optional(),
  max_candidates: z.number().int().min(1).optional(),
  registered_count: z.number().int().min(0).optional(),
  status: z.enum(['planned', 'registration_open', 'registration_closed', 'in_progress', 'completed', 'cancelled']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── International Credits ────────────────────────────────────────────────

export const internationalCreditsCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  source_institution: z.string().min(1).max(300),
  source_country: z.string().min(1).max(100),
  source_credits: z.number().int().min(0),
  source_scale: z.string().max(100).optional(),
  converted_credits: z.number().int().min(0),
  target_scale: z.string().max(100).optional(),
  conversion_method: z.enum(['ects', 'us_credit', 'direct_transfer', 'credential_evaluation']),
  equivalence_percentage: z.number().min(0).max(100).optional(),
  course_details: z.array(z.object({
    course_name: z.string().max(300),
    course_code: z.string().max(50).optional(),
    original_grade: z.string().max(20).optional(),
    credits: z.number().int().min(0),
    subject_area: z.string().max(200).optional(),
  })).optional(),
  evaluation_date: z.string().datetime(),
  evaluated_by: z.string().uuid().optional(),
  status: z.enum(['pending', 'evaluated', 'approved', 'rejected', 'appealed']).optional(),
  notes: z.string().max(5000).optional(),
});

export const internationalCreditsUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  source_institution: z.string().min(1).max(300).optional(),
  source_country: z.string().min(1).max(100).optional(),
  source_credits: z.number().int().min(0).optional(),
  source_scale: z.string().max(100).optional(),
  converted_credits: z.number().int().min(0).optional(),
  target_scale: z.string().max(100).optional(),
  conversion_method: z.enum(['ects', 'us_credit', 'direct_transfer', 'credential_evaluation']).optional(),
  equivalence_percentage: z.number().min(0).max(100).optional(),
  course_details: z.array(z.object({
    course_name: z.string().max(300),
    course_code: z.string().max(50).optional(),
    original_grade: z.string().max(20).optional(),
    credits: z.number().int().min(0),
    subject_area: z.string().max(200).optional(),
  })).optional(),
  evaluation_date: z.string().datetime().optional(),
  evaluated_by: z.string().uuid().optional(),
  status: z.enum(['pending', 'evaluated', 'approved', 'rejected', 'appealed']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Credit Transfer ──────────────────────────────────────────────────────

export const creditTransferCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  source_institution: z.string().min(1).max(300),
  target_institution: z.string().min(1).max(300),
  transfer_type: z.enum(['inbound', 'outbound', 'internal']),
  course_code: z.string().min(1).max(50),
  course_name: z.string().min(1).max(300),
  original_credits: z.number().int().min(0),
  original_grade: z.string().max(20),
  transferred_credits: z.number().int().min(0),
  equivalent_course_code: z.string().max(50).optional(),
  equivalent_course_name: z.string().max(300).optional(),
  syllabus_url: z.string().url().optional(),
  request_date: z.string().datetime(),
  reviewed_by: z.string().uuid().optional(),
  review_date: z.string().datetime().optional(),
  status: z.enum(['submitted', 'under_review', 'approved', 'denied', 'conditional']).optional(),
  conditions: z.array(z.string().max(300)).optional(),
  notes: z.string().max(5000).optional(),
});

export const creditTransferUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  source_institution: z.string().min(1).max(300).optional(),
  target_institution: z.string().min(1).max(300).optional(),
  transfer_type: z.enum(['inbound', 'outbound', 'internal']).optional(),
  course_code: z.string().min(1).max(50).optional(),
  course_name: z.string().min(1).max(300).optional(),
  original_credits: z.number().int().min(0).optional(),
  original_grade: z.string().max(20).optional(),
  transferred_credits: z.number().int().min(0).optional(),
  equivalent_course_code: z.string().max(50).optional(),
  equivalent_course_name: z.string().max(300).optional(),
  syllabus_url: z.string().url().optional(),
  request_date: z.string().datetime().optional(),
  reviewed_by: z.string().uuid().optional(),
  review_date: z.string().datetime().optional(),
  status: z.enum(['submitted', 'under_review', 'approved', 'denied', 'conditional']).optional(),
  conditions: z.array(z.string().max(300)).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Recognition Engine ───────────────────────────────────────────────────

export const recognitionEngineCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  recognition_type: z.enum(['academic_excellence', 'research', 'leadership', 'service', 'innovation', 'athletic', 'arts']),
  title: z.string().min(1).max(300),
  description: z.string().max(2000).optional(),
  awarded_by: z.string().min(1).max(200),
  award_level: z.enum(['school', 'district', 'regional', 'national', 'international']).optional(),
  award_date: z.string().datetime(),
  criteria_met: z.array(z.string().max(300)).optional(),
  evidence_urls: z.array(z.string().url()).optional(),
  certificate_id: z.string().uuid().optional(),
  verified: z.boolean().optional(),
  verified_by: z.string().uuid().optional(),
  featured: z.boolean().optional(),
  points: z.number().int().min(0).optional(),
  status: z.enum(['nominated', 'awarded', 'confirmed', 'revoked']).optional(),
  notes: z.string().max(5000).optional(),
});

export const recognitionEngineUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  recognition_type: z.enum(['academic_excellence', 'research', 'leadership', 'service', 'innovation', 'athletic', 'arts']).optional(),
  title: z.string().min(1).max(300).optional(),
  description: z.string().max(2000).optional(),
  awarded_by: z.string().min(1).max(200).optional(),
  award_level: z.enum(['school', 'district', 'regional', 'national', 'international']).optional(),
  award_date: z.string().datetime().optional(),
  criteria_met: z.array(z.string().max(300)).optional(),
  evidence_urls: z.array(z.string().url()).optional(),
  certificate_id: z.string().uuid().optional(),
  verified: z.boolean().optional(),
  verified_by: z.string().uuid().optional(),
  featured: z.boolean().optional(),
  points: z.number().int().min(0).optional(),
  status: z.enum(['nominated', 'awarded', 'confirmed', 'revoked']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Assessment AI ────────────────────────────────────────────────────────

export const assessmentAICreateSchema = z.object({
  school_id: schoolId,
  assessment_type: z.enum(['question_generation', 'auto_grading', 'feedback', 'analytics', 'prediction', 'personalization']),
  model_name: z.string().min(1).max(200),
  model_version: z.string().max(50).optional(),
  input_data: z.record(z.unknown()).optional(),
  configuration: z.object({
    temperature: z.number().min(0).max(2).optional(),
    max_tokens: z.number().int().min(1).optional(),
    top_p: z.number().min(0).max(1).optional(),
    frequency_penalty: z.number().min(-2).max(2).optional(),
    presence_penalty: z.number().min(-2).max(2).optional(),
  }).optional(),
  target_subject: z.string().max(200).optional(),
  target_level: z.string().max(100).optional(),
  language: z.string().min(2).max(10).optional(),
  status: z.enum(['configured', 'running', 'completed', 'failed', 'paused']).optional(),
  output_data: z.record(z.unknown()).optional(),
  started_at: z.string().datetime().optional(),
  completed_at: z.string().datetime().optional(),
  error_message: z.string().max(2000).optional(),
  notes: z.string().max(5000).optional(),
});

export const assessmentAIUpdateSchema = z.object({
  school_id: schoolId,
  assessment_type: z.enum(['question_generation', 'auto_grading', 'feedback', 'analytics', 'prediction', 'personalization']).optional(),
  model_name: z.string().min(1).max(200).optional(),
  model_version: z.string().max(50).optional(),
  input_data: z.record(z.unknown()).optional(),
  configuration: z.object({
    temperature: z.number().min(0).max(2).optional(),
    max_tokens: z.number().int().min(1).optional(),
    top_p: z.number().min(0).max(1).optional(),
    frequency_penalty: z.number().min(-2).max(2).optional(),
    presence_penalty: z.number().min(-2).max(2).optional(),
  }).optional(),
  target_subject: z.string().max(200).optional(),
  target_level: z.string().max(100).optional(),
  language: z.string().min(2).max(10).optional(),
  status: z.enum(['configured', 'running', 'completed', 'failed', 'paused']).optional(),
  output_data: z.record(z.unknown()).optional(),
  started_at: z.string().datetime().optional(),
  completed_at: z.string().datetime().optional(),
  error_message: z.string().max(2000).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Auto Feedback ────────────────────────────────────────────────────────

export const autoFeedbackCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  assignment_id: z.string().uuid().optional(),
  exam_id: z.string().uuid().optional(),
  question_id: z.string().uuid().optional(),
  feedback_type: z.enum(['correctness', 'completeness', 'clarity', 'style', 'improvement', 'encouragement']),
  original_answer: z.string().max(10000).optional(),
  feedback_text: z.string().min(1).max(5000),
  feedback_rich: z.record(z.unknown()).optional(),
  confidence_score: z.number().min(0).max(1).optional(),
  improvement_suggestions: z.array(z.string().max(500)).optional(),
  model_used: z.string().max(200).optional(),
  generated_at: z.string().datetime().optional(),
  student_read: z.boolean().optional(),
  student_read_at: z.string().datetime().optional(),
  status: z.enum(['generated', 'delivered', 'read', 'acknowledged']).optional(),
  notes: z.string().max(5000).optional(),
});

export const autoFeedbackUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  assignment_id: z.string().uuid().optional(),
  exam_id: z.string().uuid().optional(),
  question_id: z.string().uuid().optional(),
  feedback_type: z.enum(['correctness', 'completeness', 'clarity', 'style', 'improvement', 'encouragement']).optional(),
  original_answer: z.string().max(10000).optional(),
  feedback_text: z.string().min(1).max(5000).optional(),
  feedback_rich: z.record(z.unknown()).optional(),
  confidence_score: z.number().min(0).max(1).optional(),
  improvement_suggestions: z.array(z.string().max(500)).optional(),
  model_used: z.string().max(200).optional(),
  generated_at: z.string().datetime().optional(),
  student_read: z.boolean().optional(),
  student_read_at: z.string().datetime().optional(),
  status: z.enum(['generated', 'delivered', 'read', 'acknowledged']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── AI Weakness Detection ────────────────────────────────────────────────

export const aIWeaknessDetectionCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  subject: z.string().min(1).max(200),
  assessment_period: z.string().max(50),
  data_sources: z.array(z.enum(['exam_scores', 'assignment_scores', 'practice_tests', 'class_participation', 'homework'])),
  detected_weaknesses: z.array(z.object({
    topic: z.string().max(200),
    subtopic: z.string().max(200).optional(),
    weakness_level: z.enum(['mild', 'moderate', 'severe']),
    confidence: z.number().min(0).max(1),
    evidence_count: z.number().int().min(0),
    last_assessed: z.string().datetime().optional(),
  })),
  overall_weakness_score: z.number().min(0).max(1).optional(),
  recommended_resources: z.array(z.object({
    resource_type: z.enum(['practice', 'tutorial', 'video', 'reading', 'exercise']),
    resource_url: z.string().url().optional(),
    topic: z.string().max(200),
    difficulty: z.enum(['easy', 'medium', 'hard']),
  })).optional(),
  detection_date: z.string().datetime(),
  model_version: z.string().max(50).optional(),
  notes: z.string().max(5000).optional(),
});

export const aIWeaknessDetectionUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  subject: z.string().min(1).max(200).optional(),
  assessment_period: z.string().max(50).optional(),
  data_sources: z.array(z.enum(['exam_scores', 'assignment_scores', 'practice_tests', 'class_participation', 'homework'])).optional(),
  detected_weaknesses: z.array(z.object({
    topic: z.string().max(200),
    subtopic: z.string().max(200).optional(),
    weakness_level: z.enum(['mild', 'moderate', 'severe']),
    confidence: z.number().min(0).max(1),
    evidence_count: z.number().int().min(0),
    last_assessed: z.string().datetime().optional(),
  })).optional(),
  overall_weakness_score: z.number().min(0).max(1).optional(),
  recommended_resources: z.array(z.object({
    resource_type: z.enum(['practice', 'tutorial', 'video', 'reading', 'exercise']),
    resource_url: z.string().url().optional(),
    topic: z.string().max(200),
    difficulty: z.enum(['easy', 'medium', 'hard']),
  })).optional(),
  detection_date: z.string().datetime().optional(),
  model_version: z.string().max(50).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Learning Suggestion ──────────────────────────────────────────────────

export const learningSuggestionCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  subject: z.string().min(1).max(200),
  current_level: z.enum(['beginner', 'elementary', 'intermediate', 'upper_intermediate', 'advanced', 'expert']),
  target_level: z.enum(['beginner', 'elementary', 'intermediate', 'upper_intermediate', 'advanced', 'expert']),
  learning_style: z.enum(['visual', 'auditory', 'reading', 'kinesthetic', 'multimodal']).optional(),
  suggestions: z.array(z.object({
    suggestion_type: z.enum(['course', 'exercise', 'reading', 'video', 'project', 'tutoring']),
    title: z.string().max(300),
    description: z.string().max(1000),
    estimated_duration_minutes: z.number().int().min(1).optional(),
    difficulty: z.enum(['easy', 'medium', 'hard']),
    priority: z.enum(['low', 'medium', 'high']),
    resource_url: z.string().url().optional(),
  })),
  learning_path_url: z.string().url().optional(),
  estimated_completion_weeks: z.number().int().min(1).optional(),
  generated_at: z.string().datetime().optional(),
  student_viewed: z.boolean().optional(),
  student_feedback: z.enum(['helpful', 'not_helpful', 'partially_helpful']).optional(),
  status: z.enum(['generated', 'delivered', 'viewed', 'in_progress', 'completed']).optional(),
  notes: z.string().max(5000).optional(),
});

export const learningSuggestionUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  subject: z.string().min(1).max(200).optional(),
  current_level: z.enum(['beginner', 'elementary', 'intermediate', 'upper_intermediate', 'advanced', 'expert']).optional(),
  target_level: z.enum(['beginner', 'elementary', 'intermediate', 'upper_intermediate', 'advanced', 'expert']).optional(),
  learning_style: z.enum(['visual', 'auditory', 'reading', 'kinesthetic', 'multimodal']).optional(),
  suggestions: z.array(z.object({
    suggestion_type: z.enum(['course', 'exercise', 'reading', 'video', 'project', 'tutoring']),
    title: z.string().max(300),
    description: z.string().max(1000),
    estimated_duration_minutes: z.number().int().min(1).optional(),
    difficulty: z.enum(['easy', 'medium', 'hard']),
    priority: z.enum(['low', 'medium', 'high']),
    resource_url: z.string().url().optional(),
  })).optional(),
  learning_path_url: z.string().url().optional(),
  estimated_completion_weeks: z.number().int().min(1).optional(),
  generated_at: z.string().datetime().optional(),
  student_viewed: z.boolean().optional(),
  student_feedback: z.enum(['helpful', 'not_helpful', 'partially_helpful']).optional(),
  status: z.enum(['generated', 'delivered', 'viewed', 'in_progress', 'completed']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Exam Prediction ──────────────────────────────────────────────────────

export const examPredictionCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  exam_id: z.string().uuid().optional(),
  subject: z.string().min(1).max(200),
  prediction_type: z.enum(['score', 'pass_fail', 'rank', 'performance_band']),
  historical_data: z.array(z.object({
    date: z.string().datetime(),
    score: z.number().min(0).max(100),
    assessment_type: z.string().max(100),
  })),
  predicted_score: z.number().min(0).max(100).optional(),
  predicted_band: z.enum(['excellent', 'good', 'average', 'below_average', 'poor']).optional(),
  confidence_interval: z.object({
    lower: z.number().min(0).max(100),
    upper: z.number().min(0).max(100),
  }).optional(),
  probability_pass: z.number().min(0).max(1).optional(),
  risk_factors: z.array(z.string().max(200)).optional(),
  improvement_areas: z.array(z.string().max(200)).optional(),
  prediction_date: z.string().datetime(),
  exam_date: z.string().datetime().optional(),
  model_version: z.string().max(50).optional(),
  notes: z.string().max(5000).optional(),
});

export const examPredictionUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  exam_id: z.string().uuid().optional(),
  subject: z.string().min(1).max(200).optional(),
  prediction_type: z.enum(['score', 'pass_fail', 'rank', 'performance_band']).optional(),
  historical_data: z.array(z.object({
    date: z.string().datetime(),
    score: z.number().min(0).max(100),
    assessment_type: z.string().max(100),
  })).optional(),
  predicted_score: z.number().min(0).max(100).optional(),
  predicted_band: z.enum(['excellent', 'good', 'average', 'below_average', 'poor']).optional(),
  confidence_interval: z.object({
    lower: z.number().min(0).max(100),
    upper: z.number().min(0).max(100),
  }).optional(),
  probability_pass: z.number().min(0).max(1).optional(),
  risk_factors: z.array(z.string().max(200)).optional(),
  improvement_areas: z.array(z.string().max(200)).optional(),
  prediction_date: z.string().datetime().optional(),
  exam_date: z.string().datetime().optional(),
  model_version: z.string().max(50).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Certification Recommendation ─────────────────────────────────────────

export const certificationRecommendationCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  certification_name: z.string().min(1).max(300),
  certifying_body: z.string().min(1).max(300),
  certification_level: z.string().max(100).optional(),
  match_score: z.number().min(0).max(100),
  current_skills: z.array(z.string().max(200)).optional(),
  required_skills: z.array(z.string().max(200)).optional(),
  skill_gaps: z.array(z.string().max(200)).optional(),
  estimated_preparation_weeks: z.number().int().min(1).optional(),
  estimated_cost: z.number().min(0).optional(),
  career_benefit: z.string().max(1000).optional(),
  recommended_resources: z.array(z.object({
    resource_type: z.enum(['course', 'book', 'practice_exam', 'bootcamp', 'mentor']),
    title: z.string().max(300),
    url: z.string().url().optional(),
    cost: z.number().min(0).optional(),
  })).optional(),
  recommendation_date: z.string().datetime(),
  student_viewed: z.boolean().optional(),
  student_interested: z.boolean().optional(),
  status: z.enum(['recommended', 'viewed', 'interested', 'enrolled', 'achieved', 'expired']).optional(),
  notes: z.string().max(5000).optional(),
});

export const certificationRecommendationUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  certification_name: z.string().min(1).max(300).optional(),
  certifying_body: z.string().min(1).max(300).optional(),
  certification_level: z.string().max(100).optional(),
  match_score: z.number().min(0).max(100).optional(),
  current_skills: z.array(z.string().max(200)).optional(),
  required_skills: z.array(z.string().max(200)).optional(),
  skill_gaps: z.array(z.string().max(200)).optional(),
  estimated_preparation_weeks: z.number().int().min(1).optional(),
  estimated_cost: z.number().min(0).optional(),
  career_benefit: z.string().max(1000).optional(),
  recommended_resources: z.array(z.object({
    resource_type: z.enum(['course', 'book', 'practice_exam', 'bootcamp', 'mentor']),
    title: z.string().max(300),
    url: z.string().url().optional(),
    cost: z.number().min(0).optional(),
  })).optional(),
  recommendation_date: z.string().datetime().optional(),
  student_viewed: z.boolean().optional(),
  student_interested: z.boolean().optional(),
  status: z.enum(['recommended', 'viewed', 'interested', 'enrolled', 'achieved', 'expired']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Performance Forecast ─────────────────────────────────────────────────

export const performanceForecastCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  subject: z.string().min(1).max(200),
  forecast_type: z.enum(['semester', 'year', 'course', 'program']),
  historical_performance: z.array(z.object({
    period: z.string().max(50),
    score: z.number().min(0).max(100),
    grade: z.string().max(10).optional(),
    percentile: z.number().min(0).max(100).optional(),
  })),
  predicted_performance: z.object({
    predicted_score: z.number().min(0).max(100),
    predicted_grade: z.string().max(10).optional(),
    predicted_percentile: z.number().min(0).max(100).optional(),
    confidence: z.number().min(0).max(1),
  }),
  trend: z.enum(['improving', 'stable', 'declining']),
  contributing_factors: z.array(z.object({
    factor: z.string().max(200),
    impact: z.enum(['positive', 'negative', 'neutral']),
    magnitude: z.number().min(0).max(1),
  })).optional(),
  recommendations: z.array(z.string().max(500)).optional(),
  forecast_date: z.string().datetime(),
  target_date: z.string().datetime().optional(),
  model_version: z.string().max(50).optional(),
  notes: z.string().max(5000).optional(),
});

export const performanceForecastUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  subject: z.string().min(1).max(200).optional(),
  forecast_type: z.enum(['semester', 'year', 'course', 'program']).optional(),
  historical_performance: z.array(z.object({
    period: z.string().max(50),
    score: z.number().min(0).max(100),
    grade: z.string().max(10).optional(),
    percentile: z.number().min(0).max(100).optional(),
  })).optional(),
  predicted_performance: z.object({
    predicted_score: z.number().min(0).max(100),
    predicted_grade: z.string().max(10).optional(),
    predicted_percentile: z.number().min(0).max(100).optional(),
    confidence: z.number().min(0).max(1),
  }).optional(),
  trend: z.enum(['improving', 'stable', 'declining']).optional(),
  contributing_factors: z.array(z.object({
    factor: z.string().max(200),
    impact: z.enum(['positive', 'negative', 'neutral']),
    magnitude: z.number().min(0).max(1),
  })).optional(),
  recommendations: z.array(z.string().max(500)).optional(),
  forecast_date: z.string().datetime().optional(),
  target_date: z.string().datetime().optional(),
  model_version: z.string().max(50).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Risk Detection AI ────────────────────────────────────────────────────

export const riskDetectionAICreateSchema = z.object({
  school_id: schoolId,
  risk_type: z.enum(['dropout', 'academic_failure', 'integrity_violation', 'engagement_decline', 'financial_hardship', 'wellbeing']),
  student_id: z.string().uuid().optional(),
  cohort_id: z.string().uuid().optional(),
  risk_level: z.enum(['low', 'moderate', 'high', 'critical']),
  risk_score: z.number().min(0).max(1),
  risk_indicators: z.array(z.object({
    indicator: z.string().max(200),
    weight: z.number().min(0).max(1),
    current_value: z.string().max(200),
    threshold: z.string().max(200).optional(),
  })),
  historical_trend: z.array(z.enum(['increasing', 'stable', 'decreasing'])).optional(),
  early_warning_signals: z.array(z.string().max(300)).optional(),
  recommended_interventions: z.array(z.object({
    intervention_type: z.enum(['academic_support', 'counseling', 'financial_aid', 'mentoring', 'parent_contact']),
    description: z.string().max(500),
    priority: z.enum(['low', 'medium', 'high']),
    assigned_to: z.string().uuid().optional(),
  })).optional(),
  detection_date: z.string().datetime(),
  model_version: z.string().max(50).optional(),
  status: z.enum(['detected', 'acknowledged', 'intervening', 'resolved', 'escalated']).optional(),
  notes: z.string().max(5000).optional(),
});

export const riskDetectionAIUpdateSchema = z.object({
  school_id: schoolId,
  risk_type: z.enum(['dropout', 'academic_failure', 'integrity_violation', 'engagement_decline', 'financial_hardship', 'wellbeing']).optional(),
  student_id: z.string().uuid().optional(),
  cohort_id: z.string().uuid().optional(),
  risk_level: z.enum(['low', 'moderate', 'high', 'critical']).optional(),
  risk_score: z.number().min(0).max(1).optional(),
  risk_indicators: z.array(z.object({
    indicator: z.string().max(200),
    weight: z.number().min(0).max(1),
    current_value: z.string().max(200),
    threshold: z.string().max(200).optional(),
  })).optional(),
  historical_trend: z.array(z.enum(['increasing', 'stable', 'decreasing'])).optional(),
  early_warning_signals: z.array(z.string().max(300)).optional(),
  recommended_interventions: z.array(z.object({
    intervention_type: z.enum(['academic_support', 'counseling', 'financial_aid', 'mentoring', 'parent_contact']),
    description: z.string().max(500),
    priority: z.enum(['low', 'medium', 'high']),
    assigned_to: z.string().uuid().optional(),
  })).optional(),
  detection_date: z.string().datetime().optional(),
  model_version: z.string().max(50).optional(),
  status: z.enum(['detected', 'acknowledged', 'intervening', 'resolved', 'escalated']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Smart Rubric ─────────────────────────────────────────────────────────

export const smartRubricCreateSchema = z.object({
  school_id: schoolId,
  rubric_name: z.string().min(1).max(300),
  subject: z.string().min(1).max(200),
  assessment_type: z.enum(['essay', 'project', 'presentation', 'practical', 'portfolio', 'coding']),
  ai_enhanced: z.boolean().optional(),
  criteria: z.array(z.object({
    criterion_name: z.string().max(200),
    description: z.string().max(500),
    weight: z.number().min(0).max(1),
    levels: z.array(z.object({
      level_name: z.string().max(100),
      score: z.number().int().min(0),
      description: z.string().max(500),
      examples: z.array(z.string().max(300)).optional(),
    })),
    ai_scoring_enabled: z.boolean().optional(),
    ai_keywords: z.array(z.string().max(100)).optional(),
  })).min(1),
  max_score: z.number().int().min(1),
  passing_score: z.number().int().min(0).optional(),
  ai_scoring_accuracy: z.number().min(0).max(1).optional(),
  version: z.string().max(20).optional(),
  status: z.enum(['draft', 'active', 'archived']).optional(),
  created_by: z.string().uuid().optional(),
  notes: z.string().max(5000).optional(),
});

export const smartRubricUpdateSchema = z.object({
  school_id: schoolId,
  rubric_name: z.string().min(1).max(300).optional(),
  subject: z.string().min(1).max(200).optional(),
  assessment_type: z.enum(['essay', 'project', 'presentation', 'practical', 'portfolio', 'coding']).optional(),
  ai_enhanced: z.boolean().optional(),
  criteria: z.array(z.object({
    criterion_name: z.string().max(200),
    description: z.string().max(500),
    weight: z.number().min(0).max(1),
    levels: z.array(z.object({
      level_name: z.string().max(100),
      score: z.number().int().min(0),
      description: z.string().max(500),
      examples: z.array(z.string().max(300)).optional(),
    })),
    ai_scoring_enabled: z.boolean().optional(),
    ai_keywords: z.array(z.string().max(100)).optional(),
  })).optional(),
  max_score: z.number().int().min(1).optional(),
  passing_score: z.number().int().min(0).optional(),
  ai_scoring_accuracy: z.number().min(0).max(1).optional(),
  version: z.string().max(20).optional(),
  status: z.enum(['draft', 'active', 'archived']).optional(),
  created_by: z.string().uuid().optional(),
  notes: z.string().max(5000).optional(),
});

// ── AI Moderation ────────────────────────────────────────────────────────

export const aIModerationCreateSchema = z.object({
  school_id: schoolId,
  exam_id: z.string().uuid().optional(),
  session_id: z.string().uuid().optional(),
  moderation_type: z.enum(['auto_flag', 'proctor_intervention', 'score_adjustment', 'question_review', 'content_filter']),
  target_entity_type: z.enum(['student', 'question', 'answer', 'behavior', 'content']),
  target_entity_id: z.string().uuid().optional(),
  ai_confidence: z.number().min(0).max(1),
  flag_reason: z.string().min(1).max(500),
  flag_severity: z.enum(['info', 'warning', 'critical']),
  auto_action_taken: z.enum(['none', 'flagged', 'score_hold', 'session_paused', 'alert_sent']).optional(),
  human_review_required: z.boolean().optional(),
  reviewed_by: z.string().uuid().optional(),
  review_decision: z.enum(['confirmed', 'overturned', 'modified', 'pending']).optional(),
  review_notes: z.string().max(2000).optional(),
  detected_at: z.string().datetime(),
  reviewed_at: z.string().datetime().optional(),
  status: z.enum(['detected', 'pending_review', 'reviewed', 'resolved', 'dismissed']).optional(),
  notes: z.string().max(5000).optional(),
});

export const aIModerationUpdateSchema = z.object({
  school_id: schoolId,
  exam_id: z.string().uuid().optional(),
  session_id: z.string().uuid().optional(),
  moderation_type: z.enum(['auto_flag', 'proctor_intervention', 'score_adjustment', 'question_review', 'content_filter']).optional(),
  target_entity_type: z.enum(['student', 'question', 'answer', 'behavior', 'content']).optional(),
  target_entity_id: z.string().uuid().optional(),
  ai_confidence: z.number().min(0).max(1).optional(),
  flag_reason: z.string().min(1).max(500).optional(),
  flag_severity: z.enum(['info', 'warning', 'critical']).optional(),
  auto_action_taken: z.enum(['none', 'flagged', 'score_hold', 'session_paused', 'alert_sent']).optional(),
  human_review_required: z.boolean().optional(),
  reviewed_by: z.string().uuid().optional(),
  review_decision: z.enum(['confirmed', 'overturned', 'modified', 'pending']).optional(),
  review_notes: z.string().max(2000).optional(),
  detected_at: z.string().datetime().optional(),
  reviewed_at: z.string().datetime().optional(),
  status: z.enum(['detected', 'pending_review', 'reviewed', 'resolved', 'dismissed']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── AI Invigilator ───────────────────────────────────────────────────────

export const aIInvigilatorCreateSchema = z.object({
  school_id: schoolId,
  exam_id: z.string().uuid(),
  session_id: z.string().uuid().optional(),
  student_id: z.string().uuid().optional(),
  invigilation_mode: z.enum(['full_auto', 'semi_auto', 'human_supervised']),
  features_enabled: z.array(z.enum([
    'face_detection', 'gaze_tracking', 'object_detection', 'audio_monitoring',
    'tab_switch_detection', 'copy_paste_detection', 'screen_recording',
    'identity_verification', 'environment_scan', 'behavioral_analysis',
  ])),
  alert_threshold: z.enum(['low', 'medium', 'high']),
  recording_enabled: z.boolean().optional(),
  live_proctor_id: z.string().uuid().optional(),
  alerts_generated: z.array(z.object({
    alert_type: z.string().max(200),
    timestamp: z.string().datetime(),
    severity: z.enum(['info', 'warning', 'critical']),
    description: z.string().max(500),
    auto_action: z.string().max(200).optional(),
  })).optional(),
  session_duration_minutes: z.number().int().min(0).optional(),
  total_alerts: z.number().int().min(0).optional(),
  status: z.enum(['initialized', 'active', 'completed', 'paused', 'terminated']).optional(),
  started_at: z.string().datetime().optional(),
  ended_at: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

export const aIInvigilatorUpdateSchema = z.object({
  school_id: schoolId,
  exam_id: z.string().uuid().optional(),
  session_id: z.string().uuid().optional(),
  student_id: z.string().uuid().optional(),
  invigilation_mode: z.enum(['full_auto', 'semi_auto', 'human_supervised']).optional(),
  features_enabled: z.array(z.enum([
    'face_detection', 'gaze_tracking', 'object_detection', 'audio_monitoring',
    'tab_switch_detection', 'copy_paste_detection', 'screen_recording',
    'identity_verification', 'environment_scan', 'behavioral_analysis',
  ])).optional(),
  alert_threshold: z.enum(['low', 'medium', 'high']).optional(),
  recording_enabled: z.boolean().optional(),
  live_proctor_id: z.string().uuid().optional(),
  alerts_generated: z.array(z.object({
    alert_type: z.string().max(200),
    timestamp: z.string().datetime(),
    severity: z.enum(['info', 'warning', 'critical']),
    description: z.string().max(500),
    auto_action: z.string().max(200).optional(),
  })).optional(),
  session_duration_minutes: z.number().int().min(0).optional(),
  total_alerts: z.number().int().min(0).optional(),
  status: z.enum(['initialized', 'active', 'completed', 'paused', 'terminated']).optional(),
  started_at: z.string().datetime().optional(),
  ended_at: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

// ── Assessment Dashboard ─────────────────────────────────────────────────

export const assessmentDashboardCreateSchema = z.object({
  school_id: schoolId,
  dashboard_name: z.string().min(1).max(300),
  dashboard_type: z.enum(['admin', 'teacher', 'student', 'parent', 'department', 'analytics']),
  layout: z.array(z.object({
    widget_id: z.string().max(100),
    widget_type: z.enum(['chart', 'table', 'metric', 'list', 'calendar', 'map', 'gauge']),
    title: z.string().max(200),
    position: z.object({
      x: z.number().int().min(0),
      y: z.number().int().min(0),
      w: z.number().int().min(1),
      h: z.number().int().min(1),
    }),
    data_source: z.string().max(200).optional(),
    refresh_interval_seconds: z.number().int().min(0).optional(),
    filters: z.record(z.unknown()).optional(),
  })),
  default_filters: z.record(z.unknown()).optional(),
  auto_refresh: z.boolean().optional(),
  refresh_interval_seconds: z.number().int().min(0).optional(),
  date_range: z.enum(['today', 'week', 'month', 'quarter', 'year', 'custom']).optional(),
  shared_with: z.array(z.string().uuid()).optional(),
  is_default: z.boolean().optional(),
  status: z.enum(['draft', 'active', 'archived']).optional(),
  created_by: z.string().uuid().optional(),
  notes: z.string().max(5000).optional(),
});

export const assessmentDashboardUpdateSchema = z.object({
  school_id: schoolId,
  dashboard_name: z.string().min(1).max(300).optional(),
  dashboard_type: z.enum(['admin', 'teacher', 'student', 'parent', 'department', 'analytics']).optional(),
  layout: z.array(z.object({
    widget_id: z.string().max(100),
    widget_type: z.enum(['chart', 'table', 'metric', 'list', 'calendar', 'map', 'gauge']),
    title: z.string().max(200),
    position: z.object({
      x: z.number().int().min(0),
      y: z.number().int().min(0),
      w: z.number().int().min(1),
      h: z.number().int().min(1),
    }),
    data_source: z.string().max(200).optional(),
    refresh_interval_seconds: z.number().int().min(0).optional(),
    filters: z.record(z.unknown()).optional(),
  })).optional(),
  default_filters: z.record(z.unknown()).optional(),
  auto_refresh: z.boolean().optional(),
  refresh_interval_seconds: z.number().int().min(0).optional(),
  date_range: z.enum(['today', 'week', 'month', 'quarter', 'year', 'custom']).optional(),
  shared_with: z.array(z.string().uuid()).optional(),
  is_default: z.boolean().optional(),
  status: z.enum(['draft', 'active', 'archived']).optional(),
  created_by: z.string().uuid().optional(),
  notes: z.string().max(5000).optional(),
});

// ── Exam Taking State ────────────────────────────────────────────────────

export const examTakingStateCreateSchema = z.object({
  school_id: schoolId,
  exam_id: z.string().uuid(),
  student_id: z.string().uuid(),
  session_id: z.string().uuid().optional(),
  current_question_index: z.number().int().min(0).optional(),
  answers: z.record(z.unknown()).optional(),
  flagged_questions: z.array(z.number().int().min(0)).optional(),
  time_spent_seconds: z.record(z.number().int().min(0)).optional(),
  total_time_spent_seconds: z.number().int().min(0).optional(),
  time_remaining_seconds: z.number().int().min(0).optional(),
  status: z.enum(['not_started', 'in_progress', 'paused', 'submitted', 'timed_out']).optional(),
  started_at: z.string().datetime().optional(),
  last_saved_at: z.string().datetime().optional(),
  submitted_at: z.string().datetime().optional(),
  auto_save_enabled: z.boolean().optional(),
  proctor_alerts: z.number().int().min(0).optional(),
  tab_switch_count: z.number().int().min(0).optional(),
  ip_address: z.string().max(45).optional(),
  user_agent: z.string().max(500).optional(),
  notes: z.string().max(5000).optional(),
});

export const examTakingStateUpdateSchema = z.object({
  school_id: schoolId,
  exam_id: z.string().uuid().optional(),
  student_id: z.string().uuid().optional(),
  session_id: z.string().uuid().optional(),
  current_question_index: z.number().int().min(0).optional(),
  answers: z.record(z.unknown()).optional(),
  flagged_questions: z.array(z.number().int().min(0)).optional(),
  time_spent_seconds: z.record(z.number().int().min(0)).optional(),
  total_time_spent_seconds: z.number().int().min(0).optional(),
  time_remaining_seconds: z.number().int().min(0).optional(),
  status: z.enum(['not_started', 'in_progress', 'paused', 'submitted', 'timed_out']).optional(),
  started_at: z.string().datetime().optional(),
  last_saved_at: z.string().datetime().optional(),
  submitted_at: z.string().datetime().optional(),
  auto_save_enabled: z.boolean().optional(),
  proctor_alerts: z.number().int().min(0).optional(),
  tab_switch_count: z.number().int().min(0).optional(),
  ip_address: z.string().max(45).optional(),
  user_agent: z.string().max(500).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Certificate Wallet ───────────────────────────────────────────────────

export const certificateWalletCreateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid(),
  wallet_name: z.string().min(1).max(200),
  certificates: z.array(z.object({
    certificate_id: z.string().uuid(),
    added_date: z.string().datetime(),
    verified: z.boolean().optional(),
    verified_at: z.string().datetime().optional(),
    shared: z.boolean().optional(),
    share_count: z.number().int().min(0).optional(),
  })).optional(),
  total_certificates: z.number().int().min(0).optional(),
  total_skill_badges: z.number().int().min(0).optional(),
  verification_count: z.number().int().min(0).optional(),
  public_sharing_enabled: z.boolean().optional(),
  wallet_url: z.string().url().optional(),
  display_name: z.string().max(200).optional(),
  bio: z.string().max(1000).optional(),
  profile_image_url: z.string().url().optional(),
  status: z.enum(['active', 'inactive', 'archived']).optional(),
  created_at: z.string().datetime().optional(),
  last_updated_at: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
});

export const certificateWalletUpdateSchema = z.object({
  school_id: schoolId,
  student_id: z.string().uuid().optional(),
  wallet_name: z.string().min(1).max(200).optional(),
  certificates: z.array(z.object({
    certificate_id: z.string().uuid(),
    added_date: z.string().datetime(),
    verified: z.boolean().optional(),
    verified_at: z.string().datetime().optional(),
    shared: z.boolean().optional(),
    share_count: z.number().int().min(0).optional(),
  })).optional(),
  total_certificates: z.number().int().min(0).optional(),
  total_skill_badges: z.number().int().min(0).optional(),
  verification_count: z.number().int().min(0).optional(),
  public_sharing_enabled: z.boolean().optional(),
  wallet_url: z.string().url().optional(),
  display_name: z.string().max(200).optional(),
  bio: z.string().max(1000).optional(),
  profile_image_url: z.string().url().optional(),
  status: z.enum(['active', 'inactive', 'archived']).optional(),
  notes: z.string().max(5000).optional(),
});

// ── Integrity Dashboard ──────────────────────────────────────────────────

export const integrityDashboardCreateSchema = z.object({
  school_id: schoolId,
  dashboard_name: z.string().min(1).max(300),
  dashboard_type: z.enum(['overview', 'incidents', 'trends', 'analytics', 'compliance']),
  time_range: z.enum(['real_time', 'today', 'week', 'month', 'quarter', 'year']),
  metrics: z.object({
    total_incidents: z.number().int().min(0).optional(),
    open_incidents: z.number().int().min(0).optional(),
    resolved_incidents: z.number().int().min(0).optional(),
    average_resolution_days: z.number().min(0).optional(),
    incidents_by_type: z.record(z.number().int().min(0)).optional(),
    incidents_by_severity: z.record(z.number().int().min(0)).optional(),
    risk_score_trend: z.array(z.number()).optional(),
    detection_rate: z.number().min(0).max(100).optional(),
    false_positive_rate: z.number().min(0).max(100).optional(),
  }).optional(),
  active_filters: z.record(z.unknown()).optional(),
  refresh_interval_seconds: z.number().int().min(0).optional(),
  alert_thresholds: z.object({
    high_risk_count: z.number().int().min(0).optional(),
    critical_incidents: z.number().int().min(0).optional(),
    unresolved_days: z.number().int().min(0).optional(),
  }).optional(),
  auto_refresh: z.boolean().optional(),
  shared_with: z.array(z.string().uuid()).optional(),
  status: z.enum(['draft', 'active', 'archived']).optional(),
  created_by: z.string().uuid().optional(),
  notes: z.string().max(5000).optional(),
});

export const integrityDashboardUpdateSchema = z.object({
  school_id: schoolId,
  dashboard_name: z.string().min(1).max(300).optional(),
  dashboard_type: z.enum(['overview', 'incidents', 'trends', 'analytics', 'compliance']).optional(),
  time_range: z.enum(['real_time', 'today', 'week', 'month', 'quarter', 'year']).optional(),
  metrics: z.object({
    total_incidents: z.number().int().min(0).optional(),
    open_incidents: z.number().int().min(0).optional(),
    resolved_incidents: z.number().int().min(0).optional(),
    average_resolution_days: z.number().min(0).optional(),
    incidents_by_type: z.record(z.number().int().min(0)).optional(),
    incidents_by_severity: z.record(z.number().int().min(0)).optional(),
    risk_score_trend: z.array(z.number()).optional(),
    detection_rate: z.number().min(0).max(100).optional(),
    false_positive_rate: z.number().min(0).max(100).optional(),
  }).optional(),
  active_filters: z.record(z.unknown()).optional(),
  refresh_interval_seconds: z.number().int().min(0).optional(),
  alert_thresholds: z.object({
    high_risk_count: z.number().int().min(0).optional(),
    critical_incidents: z.number().int().min(0).optional(),
    unresolved_days: z.number().int().min(0).optional(),
  }).optional(),
  auto_refresh: z.boolean().optional(),
  shared_with: z.array(z.string().uuid()).optional(),
  status: z.enum(['draft', 'active', 'archived']).optional(),
  created_by: z.string().uuid().optional(),
  notes: z.string().max(5000).optional(),
});
