export {
  CreateStudentSchema,
  UpdateStudentSchema,
  ArchiveStudentSchema,
  RestoreStudentSchema,
  DeleteStudentSchema,
  TransferStudentSchema,
  PromotionStudentSchema,
  GuardianSchema,
  EmergencyContactSchema,
  MedicalSchema,
  VaccinationSchema,
  PhotoSchema,
  DocumentSchema,
  QRCodeSchema,
  StudentCardSchema,
  ImportSchema,
  ExportSchema,
  FiltersSchema,
  SearchSchema,
  EnrollmentSchema,
  TimelineSchema,
  StatisticsSchema,
} from './schemas';

export type {
  CreateStudentInput,
  UpdateStudentInput,
  ArchiveStudentInput,
  RestoreStudentInput,
  DeleteStudentInput,
  TransferStudentInput,
  PromotionStudentInput,
  GuardianInput,
  EmergencyContactInput,
  MedicalInput,
  VaccinationInput,
  PhotoInput,
  DocumentInput,
  QRCodeInput,
  StudentCardInput,
  ImportInput,
  ExportInput,
  FiltersInput,
  SearchInput,
  EnrollmentInput,
  TimelineInput,
  StatisticsInput,
} from './schemas';
