export enum GovernanceLevel {
  GLOBAL = "GLOBAL",
  CONTINENTAL = "CONTINENTAL",
  REGIONAL = "REGIONAL",
  NATIONAL = "NATIONAL",
  PROVINCIAL = "PROVINCIAL",
  LOCAL = "LOCAL",
  INSTITUTIONAL = "INSTITUTIONAL",
  DEPARTMENTAL = "DEPARTMENTAL",
}

export enum PolicyStatus {
  DRAFT = "DRAFT",
  UNDER_REVIEW = "UNDER_REVIEW",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  REVISED = "REVISED",
  ARCHIVED = "ARCHIVED",
  RETIRED = "RETIRED",
  UNDER_APPEAL = "UNDER_APPEAL",
}

export enum AgreementType {
  BILATERAL = "BILATERAL",
  MULTILATERAL = "MULTILATERAL",
  REGIONAL = "REGIONAL",
  GLOBAL = "GLOBAL",
  INTERGOVERNMENTAL = "INTERGOVERNMENTAL",
  PUBLIC_PRIVATE = "PUBLIC_PRIVATE",
  ACADEMIC = "ACADEMIC",
  RESEARCH = "RESEARCH",
  MOU = "MOU",
  TREATY = "TREATY",
}

export enum LawType {
  CONSTITUTIONAL = "CONSTITUTIONAL",
  STATUTORY = "STATUTORY",
  REGULATORY = "REGULATORY",
  ADMINISTRATIVE = "ADMINISTRATIVE",
  EXECUTIVE_ORDER = "EXECUTIVE_ORDER",
  JUDICIAL = "JUDICIAL",
  CUSTOMARY = "CUSTOMARY",
  INTERNATIONAL = "INTERNATIONAL",
  SUBSIDIARY = "SUBSIDIARY",
  AMENDMENT = "AMENDMENT",
}

export enum DirectiveType {
  MANDATORY = "MANDATORY",
  RECOMMENDATION = "RECOMMENDATION",
  GUIDELINE = "GUIDELINE",
  ADVISORY = "ADVISORY",
  FRAMEWORK = "FRAMEWORK",
  STANDARD = "STANDARD",
  PROTOCOL = "PROTOCOL",
  CODE_OF_CONDUCT = "CODE_OF_CONDUCT",
  BEST_PRACTICE = "BEST_PRACTICE",
  INSTRUCTION = "INSTRUCTION",
}

export enum WorkflowStatus {
  INITIATED = "INITIATED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_REVIEW = "PENDING_REVIEW",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REVISION_REQUIRED = "REVISION_REQUIRED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  ON_HOLD = "ON_HOLD",
}

export enum ComplianceStatus {
  COMPLIANT = "COMPLIANT",
  NON_COMPLIANT = "NON_COMPLIANT",
  PARTIALLY_COMPLIANT = "PARTIALLY_COMPLIANT",
  UNDER_REVIEW = "UNDER_REVIEW",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  EXEMPT = "EXEMPT",
  WAIVED = "WAIVED",
  DEFERRED = "DEFERRED",
  IN_PROGRESS = "IN_PROGRESS",
  NOT_APPLICABLE = "NOT_APPLICABLE",
}

export enum VersionStatus {
  DRAFT = "DRAFT",
  CURRENT = "CURRENT",
  DEPRECATED = "DEPRECATED",
  ARCHIVED = "ARCHIVED",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  SUPERSEDED = "SUPERSEDED",
}

export enum AuditType {
  INTERNAL = "INTERNAL",
  EXTERNAL = "EXTERNAL",
  REGULATORY = "REGULATORY",
  FINANCIAL = "FINANCIAL",
  OPERATIONAL = "OPERATIONAL",
  COMPLIANCE = "COMPLIANCE",
  PERFORMANCE = "PERFORMANCE",
  STRATEGIC = "STRATEGIC",
  RISK = "RISK",
  QUALITY = "QUALITY",
}

export enum AnalyticsMetric {
  ENROLLMENT_RATE = "ENROLLMENT_RATE",
  LITERACY_RATE = "LITERACY_RATE",
  GRADUATION_RATE = "GRADUATION_RATE",
  TEACHER_RATIO = "TEACHER_RATIO",
  BUDGET_ALLOCATION = "BUDGET_ALLOCATION",
  INFRASTRUCTURE_INDEX = "INFRASTRUCTURE_INDEX",
  QUALITY_INDEX = "QUALITY_INDEX",
  ACCESS_INDEX = "ACCESS_INDEX",
  EQUITY_INDEX = "EQUITY_INDEX",
  OUTCOMES_INDEX = "OUTCOMES_INDEX",
}

export enum PolicyCategory {
  CURRICULUM = "CURRICULUM",
  ASSESSMENT = "ASSESSMENT",
  QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
  TEACHER_EDUCATION = "TEACHER_EDUCATION",
  STUDENT_WELFARE = "STUDENT_WELFARE",
  GOVERNANCE = "GOVERNANCE",
  FUNDING = "FUNDING",
  TECHNOLOGY = "TECHNOLOGY",
  INCLUSION = "INCLUSION",
  SUSTAINABILITY = "SUSTAINABILITY",
}

export enum EnforcementMechanism {
  MANDATORY = "MANDATORY",
  VOLUNTARY = "VOLUNTARY",
  INCENTIVE_BASED = "INCENTIVE_BASED",
  PENALTY_BASED = "PENALTY_BASED",
  MONITORING = "MONITORING",
  SELF_REGULATION = "SELF_REGULATION",
  PEER_REVIEW = "PEER_REVIEW",
  INSPECTION = "INSPECTION",
}

export enum RegionalBloc {
  AU = "AU",
  ECOWAS = "ECOWAS",
  EU = "EU",
  ASEAN = "ASEAN",
  MERCOSUR = "MERCOSUR",
  CARICOM = "CARICOM",
  SAARC = "SAARC",
  GCC = "GCC",
  NAFTA = "NAFTA",
  SADC = "SADC",
}

export enum InternationalFramework {
  SDG4 = "SDG4",
  EFA = "EFA",
  ESD = "ESD",
  CEF = "CEF",
  ISCED = "ISCED",
  EQF = "EQF",
  UNESCO_CONVENTION = "UNESCO_CONVENTION",
  WORLD_BANK_EDUCATION = "WORLD_BANK_EDUCATION",
  OECD_EDUCATION = "OECD_EDUCATION",
  AGENDA_2063 = "AGENDA_2063",
}

export enum ComplianceArea {
  CURRICULUM = "CURRICULUM",
  ASSESSMENT = "ASSESSMENT",
  QUALIFICATION = "QUALIFICATION",
  CREDENTIAL = "CREDENTIAL",
  DATA_PRIVACY = "DATA_PRIVACY",
  ACCESSIBILITY = "ACCESSIBILITY",
  SAFETY = "SAFETY",
  ETHICS = "ETHICS",
  TRANSPARENCY = "TRANSPARENCY",
  ACCOUNTABILITY = "ACCOUNTABILITY",
}

export enum PolicyImpact {
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
  CRITICAL = "CRITICAL",
  NEGLIGIBLE = "NEGLIGIBLE",
  TRANSFORMATIONAL = "TRANSFORMATIONAL",
  INCREMENTAL = "INCREMENTAL",
}

export enum StakeholderType {
  GOVERNMENT = "GOVERNMENT",
  NGO = "NGO",
  PRIVATE_SECTOR = "PRIVATE_SECTOR",
  ACADEMIC = "ACADEMIC",
  INTERNATIONAL = "INTERNATIONAL",
  COMMUNITY = "COMMUNITY",
  CIVIL_SOCIETY = "CIVIL_SOCIETY",
  MULTILATERAL = "MULTILATERAL",
}

export enum GovernanceRiskLevel {
  VERY_LOW = "VERY_LOW",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  VERY_HIGH = "VERY_HIGH",
  CRITICAL = "CRITICAL",
}

export enum AuditFinding {
  MAJOR_NON_CONFORMITY = "MAJOR_NON_CONFORMITY",
  MINOR_NON_CONFORMITY = "MINOR_NON_CONFORMITY",
  OBSERVATION = "OBSERVATION",
  BEST_PRACTICE = "BEST_PRACTICE",
  OPPORTUNITY_FOR_IMPROVEMENT = "OPPORTUNITY_FOR_IMPROVEMENT",
  CONFORMITY = "CONFORMITY",
  SYSTEMATIC_FINDING = "SYSTEMATIC_FINDING",
}

export enum PolicyPriority {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
  OPTIONAL = "OPTIONAL",
}

export enum GovernanceScope {
  COMPREHENSIVE = "COMPREHENSIVE",
  SECTORAL = "SECTORAL",
  TOPICAL = "TOPICAL",
  TEMPORARY = "TEMPORARY",
  EMERGENCY = "EMERGENCY",
}

export enum AgreementStatus {
  NEGOTIATION = "NEGOTIATION",
  SIGNED = "SIGNED",
  RATIFIED = "RATIFIED",
  IMPLEMENTING = "IMPLEMENTING",
  REVIEWING = "REVIEWING",
  TERMINATED = "TERMINATED",
  SUSPENDED = "SUSPENDED",
  AMENDED = "AMENDED",
}

export enum DirectiveStatus {
  DRAFT = "DRAFT",
  ISSUED = "ISSUED",
  ACTIVE = "ACTIVE",
  AMENDED = "AMENDED",
  WITHDRAWN = "WITHDRAWN",
  SUPERSEDED = "SUPERSEDED",
}

export enum ComplianceReviewType {
  SELF_ASSESSMENT = "SELF_ASSESSMENT",
  PEER_REVIEW = "PEER_REVIEW",
  EXTERNAL_AUDIT = "EXTERNAL_AUDIT",
  REGULATORY_INSPECTION = "REGULATORY_INSPECTION",
  MONITORING = "MONITORING",
  EVALUATION = "EVALUATION",
}

export enum PolicyEvidenceType {
  RESEARCH = "RESEARCH",
  DATA = "DATA",
  CASE_STUDY = "CASE_STUDY",
  EXPERT_OPINION = "EXPERT_OPINION",
  BENCHMARK = "BENCHMARK",
  SURVEY = "SURVEY",
  PILOT = "PILOT",
}

export enum GovernanceOutcome {
  IMPROVED_ACCESS = "IMPROVED_ACCESS",
  ENHANCED_QUALITY = "ENHANCED_QUALITY",
  INCREASED_EQUITY = "INCREASED_EQUITY",
  BETTER_GOVERNANCE = "BETTER_GOVERNANCE",
  CAPACITY_BUILDING = "CAPACITY_BUILDING",
  INNOVATION = "INNOVATION",
  SUSTAINABILITY = "SUSTAINABILITY",
  PARTNERSHIP = "PARTNERSHIP",
}

export enum PolicyReviewCycle {
  ANNUAL = "ANNUAL",
  BIENNIAL = "BIENNIAL",
  TRIENNIAL = "TRIENNIAL",
  QUADRENNIAL = "QUADRENNIAL",
  ON_DEMAND = "ON_DEMAND",
  EVENT_DRIVEN = "EVENT_DRIVEN",
}

export enum ComplianceEnforcementLevel {
  WARNING = "WARNING",
  SANCTION = "SANCTION",
  PENALTY = "PENALTY",
  SUSPENSION = "SUSPENSION",
  REVOCATION = "REVOCATION",
  LEGAL_ACTION = "LEGAL_ACTION",
}

export enum InternationalOrganization {
  UNESCO = "UNESCO",
  UNICEF = "UNICEF",
  WORLD_BANK = "WORLD_BANK",
  OECD = "OECD",
  ILO = "ILO",
  WHO = "WHO",
  AFRICAN_UNION = "AFRICAN_UNION",
  EUROPEAN_UNION = "EUROPEAN_UNION",
  ASIAN_DEVELOPMENT_BANK = "ASIAN_DEVELOPMENT_BANK",
  INTER_AMERICAN_DEVELOPMENT_BANK = "INTER_AMERICAN_DEVELOPMENT_BANK",
}

export enum PolicyFrameworkType {
  NATIONAL = "NATIONAL",
  REGIONAL = "REGIONAL",
  INTERNATIONAL = "INTERNATIONAL",
  SECTORAL = "SECTORAL",
  CROSS_CUTTING = "CROSS_CUTTING",
  INSTITUTIONAL = "INSTITUTIONAL",
}

export enum ComplianceDataSource {
  SELF_REPORTED = "SELF_REPORTED",
  VERIFIED = "VERIFIED",
  THIRD_PARTY = "THIRD_PARTY",
  AUTOMATED = "AUTOMATED",
  SURVEY = "SURVEY",
  OBSERVATION = "OBSERVATION",
}

export enum GovernanceTransparency {
  FULL = "FULL",
  PARTIAL = "PARTIAL",
  LIMITED = "LIMITED",
  RESTRICTED = "RESTRICTED",
  CONFIDENTIAL = "CONFIDENTIAL",
}

export enum PolicyStakeholderRole {
  DEVELOPER = "DEVELOPER",
  REVIEWER = "REVIEWER",
  APPROVER = "APPROVER",
  IMPLEMENTER = "IMPLEMENTER",
  MONITOR = "MONITOR",
  BENEFICIARY = "BENEFICIARY",
  OBSERVER = "OBSERVER",
}

export enum ComplianceTimeline {
  IMMEDIATE = "IMMEDIATE",
  SHORT_TERM = "SHORT_TERM",
  MEDIUM_TERM = "MEDIUM_TERM",
  LONG_TERM = "LONG_TERM",
  PHASED = "PHASED",
}

export enum GovernanceCapacity {
  STRONG = "STRONG",
  ADEQUATE = "ADEQUATE",
  DEVELOPING = "DEVELOPING",
  WEAK = "WEAK",
  CRITICALLY_LOW = "CRITICALLY_LOW",
}

export enum PolicyEffectiveness {
  HIGHLY_EFFECTIVE = "HIGHLY_EFFECTIVE",
  EFFECTIVE = "EFFECTIVE",
  PARTIALLY_EFFECTIVE = "PARTIALLY_EFFECTIVE",
  INEFFECTIVE = "INEFFECTIVE",
  COUNTERPRODUCTIVE = "COUNTERPRODUCTIVE",
}

export enum ComplianceReportingFrequency {
  REAL_TIME = "REAL_TIME",
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  ANNUAL = "ANNUAL",
  AD_HOC = "AD_HOC",
}

export enum GovernanceMaturityLevel {
  INITIAL = "INITIAL",
  DEVELOPING = "DEVELOPING",
  DEFINED = "DEFINED",
  MANAGED = "MANAGED",
  OPTIMIZING = "OPTIMIZING",
}

export enum InternationalCollaborationType {
  RESEARCH = "RESEARCH",
  CAPACITY_BUILDING = "CAPACITY_BUILDING",
  POLICY_DIALOGUE = "POLICY_DIALOGUE",
  TECHNICAL_ASSISTANCE = "TECHNICAL_ASSISTANCE",
  EXCHANGE = "EXCHANGE",
  JOINT_PROGRAM = "JOINT_PROGRAM",
  SOUTH_SOUTH = "SOUTH_SOUTH",
  TRIANGULAR = "TRIANGULAR",
}

export enum ComplianceStandard {
  ISO_9001 = "ISO_9001",
  ISO_14001 = "ISO_14001",
  ISO_27001 = "ISO_27001",
  UNESCO_GUIDELINES = "UNESCO_GUIDELINES",
  WORLD_BANK_SAFEGUARDS = "WORLD_BANK_SAFEGUARDS",
  OECD_PRINCIPLES = "OECD_PRINCIPLES",
  LOCAL_REGULATION = "LOCAL_REGULATION",
}

export enum PolicyImplementationPhase {
  PLANNING = "PLANNING",
  PILOTING = "PILOTING",
  ROLLING_OUT = "ROLLING_OUT",
  SCALING = "SCALING",
  SUSTAINING = "SUSTAINING",
  EVALUATING = "EVALUATING",
  ADJUSTING = "ADJUSTING",
}

export enum GovernanceAccountability {
  FULL = "FULL",
  SHARED = "SHARED",
  DISTRIBUTED = "DISTRIBUTED",
  LIMITED = "LIMITED",
  NONE = "NONE",
}

export enum ComplianceRiskCategory {
  OPERATIONAL = "OPERATIONAL",
  FINANCIAL = "FINANCIAL",
  REPUTATIONAL = "REPUTATIONAL",
  LEGAL = "LEGAL",
  STRATEGIC = "STRATEGIC",
  TECHNOLOGY = "TECHNOLOGY",
  ENVIRONMENTAL = "ENVIRONMENTAL",
}

export enum PolicyCommunicationChannel {
  OFFICIAL_GAZETTE = "OFFICIAL_GAZETTE",
  WEBSITE = "WEBSITE",
  EMAIL = "EMAIL",
  PRESS_RELEASE = "PRESS_RELEASE",
  CONFERENCE = "CONFERENCE",
  WORKSHOP = "WORKSHOP",
  SOCIAL_MEDIA = "SOCIAL_MEDIA",
}

export enum GovernanceDecisionType {
  UNANIMOUS = "UNANIMOUS",
  MAJORITY = "MAJORITY",
  CONSENSUS = "CONSENSUS",
  DELEGATED = "DELEGATED",
  EMERGENCY = "EMERGENCY",
}

export enum ComplianceEvidenceFormat {
  DOCUMENT = "DOCUMENT",
  DATA = "DATA",
  PHOTO = "PHOTO",
  VIDEO = "VIDEO",
  TESTIMONY = "TESTIMONY",
  CERTIFICATE = "CERTIFICATE",
}

export enum PolicyEvaluationMethod {
  FORMATIVE = "FORMATIVE",
  SUMMATIVE = "SUMMATIVE",
  PROCESS = "PROCESS",
  IMPACT = "IMPACT",
  COST_EFFECTIVENESS = "COST_EFFECTIVENESS",
  BENCHMARKING = "BENCHMARKING",
}

export enum GovernanceCollaborationLevel {
  INFORMATION_SHARING = "INFORMATION_SHARING",
  COORDINATION = "COORDINATION",
  COOPERATION = "COOPERATION",
  COLLABORATION = "COLLABORATION",
  PARTNERSHIP = "PARTNERSHIP",
  INTEGRATION = "INTEGRATION",
}

export enum ComplianceTimelineStatus {
  ON_TRACK = "ON_TRACK",
  DELAYED = "DELAYED",
  AHEAD = "AHEAD",
  BLOCKED = "BLOCKED",
  COMPLETED = "COMPLETED",
}

export enum PolicyAdaptationType {
  CONTEXTUALIZATION = "CONTEXTUALIZATION",
  TRANSLATION = "TRANSLATION",
  CULTURAL_ADAPTATION = "CULTURAL_ADAPTATION",
  SCALE_ADAPTATION = "SCALE_ADAPTATION",
  SECTOR_ADAPTATION = "SECTOR_ADAPTATION",
}

export enum GovernanceInclusionType {
  GENDER = "GENDER",
  DISABILITY = "DISABILITY",
  INDIGENOUS = "INDIGENOUS",
  MINORITY = "MINORITY",
  REFUGEE = "REFUGEE",
  RURAL = "RURAL",
  URBAN = "URBAN",
}

export enum ComplianceVerificationMethod {
  DOCUMENT_REVIEW = "DOCUMENT_REVIEW",
  SITE_VISIT = "SITE_VISIT",
  INTERVIEW = "INTERVIEW",
  SURVEY = "SURVEY",
  DATA_ANALYSIS = "DATA_ANALYSIS",
  THIRD_PARTY = "THIRD_PARTY",
}

export enum PolicySustainabilityType {
  ENVIRONMENTAL = "ENVIRONMENTAL",
  FINANCIAL = "FINANCIAL",
  INSTITUTIONAL = "INSTITUTIONAL",
  SOCIAL = "SOCIAL",
  TECHNICAL = "TECHNICAL",
}

export enum GovernanceConflictResolution {
  NEGOTIATION = "NEGOTIATION",
  MEDIATION = "MEDIATION",
  ARBITRATION = "ARBITRATION",
  LITIGATION = "LITIGATION",
  CONSENSUS = "CONSENSUS",
}

export enum ComplianceCapacityLevel {
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
  NONE = "NONE",
}

export enum PolicyBenchmarkingType {
  INTERNATIONAL = "INTERNATIONAL",
  REGIONAL = "REGIONAL",
  NATIONAL = "NATIONAL",
  SECTORAL = "SECTORAL",
  HISTORICAL = "HISTORICAL",
}

export enum GovernanceStakeholderEngagement {
  CONSULTATION = "CONSULTATION",
  PARTICIPATION = "PARTICIPATION",
  COLLABORATION = "COLLABORATION",
  EMPOWERMENT = "EMPOWERMENT",
  OWNERSHIP = "OWNERSHIP",
}

export enum ComplianceMonitoringType {
  CONTINUOUS = "CONTINUOUS",
  PERIODIC = "PERIODIC",
  RANDOM = "RANDOM",
  EVENT_BASED = "EVENT_BASED",
  RISK_BASED = "RISK_BASED",
}

export enum PolicyDisseminationType {
  TOP_DOWN = "TOP_DOWN",
  BOTTOM_UP = "BOTTOM_UP",
  LATERAL = "LATERAL",
  NETWORK = "NETWORK",
  MASS = "MASS",
}

export enum GovernanceTransparencyLevel {
  FULL_DISCLOSURE = "FULL_DISCLOSURE",
  SELECTIVE = "SELECTIVE",
  LIMITED = "LIMITED",
  RESTRICTED = "RESTRICTED",
  CLASSIFIED = "CLASSIFIED",
}

export enum ComplianceOutcomeType {
  PASS = "PASS",
  FAIL = "FAIL",
  CONDITIONAL = "CONDITIONAL",
  PENDING = "PENDING",
  DEFERRED = "DEFERRED",
}

export enum PolicyReviewBody {
  MINISTRY = "MINISTRY",
  PARLIAMENT = "PARLIAMENT",
  COMMITTEE = "COMMITTEE",
  COMMISSION = "COMMISSION",
  COUNCIL = "COUNCIL",
  EXPERT_PANEL = "EXPERT_PANEL",
}

export enum GovernanceDataClassification {
  PUBLIC = "PUBLIC",
  INTERNAL = "INTERNAL",
  CONFIDENTIAL = "CONFIDENTIAL",
  RESTRICTED = "RESTRICTED",
  TOP_SECRET = "TOP_SECRET",
}

export enum ComplianceAuditScope {
  COMPREHENSIVE = "COMPREHENSIVE",
  FOCUSED = "FOCUSED",
  FOLLOW_UP = "FOLLOW_UP",
  SPECIAL = "SPECIAL",
  EMERGENCY = "EMERGENCY",
}

export enum PolicyNegotiationPhase {
  PREPARATION = "PREPARATION",
  EXPLORATION = "EXPLORATION",
  BARGAINING = "BARGAINING",
  CLOSING = "CLOSING",
  RATIFICATION = "RATIFICATION",
}

export enum GovernanceIntegrityLevel {
  HIGH = "HIGH",
  ADEQUATE = "ADEQUATE",
  CONCERNING = "CONCERNING",
  CRITICAL = "CRITICAL",
  COMPROMISED = "COMPROMISED",
}

export enum ComplianceCorrectiveAction {
  IMMEDIATE = "IMMEDIATE",
  SHORT_TERM = "SHORT_TERM",
  LONG_TERM = "LONG_TERM",
  SYSTEMIC = "SYSTEMIC",
  PREVENTIVE = "PREVENTIVE",
}

export enum PolicyKnowledgeManagement {
  DOCUMENTATION = "DOCUMENTATION",
  DATABASE = "DATABASE",
  COMMUNITY_OF_PRACTICE = "COMMUNITY_OF_PRACTICE",
  TRAINING = "TRAINING",
  MENTORSHIP = "MENTORSHIP",
}

export enum GovernanceLeadershipType {
  TRANSFORMATIONAL = "TRANSFORMATIONAL",
  TRANSACTIONAL = "TRANSACTIONAL",
  SERVANT = "SERVANT",
  DEMOCRATIC = "DEMOCRATIC",
  AUTOCRATIC = "AUTOCRATIC",
}

export enum ComplianceReportingFormat {
  NARRATIVE = "NARRATIVE",
  QUANTITATIVE = "QUANTITATIVE",
  MIXED = "MIXED",
  VISUAL = "VISUAL",
  DIGITAL = "DIGITAL",
}

export enum PolicyImplementationTool {
  GUIDELINE = "GUIDELINE",
  CHECKLIST = "CHECKLIST",
  MANUAL = "MANUAL",
  SOFTWARE = "SOFTWARE",
  TEMPLATE = "TEMPLATE",
  PROTOCOL = "PROTOCOL",
  TRAINING = "TRAINING",
}
