export { BaseGedkinService, createGedkinService, type GedkinServiceConfig } from './base-gedkin-service';
export { DataFabricService } from './data-fabric-service';
export { DataQualityService } from './data-quality-service';
export { KnowledgeGraphService } from './knowledge-graph-service';
export { EntityResolutionService } from './entity-resolution-service';
export { SemanticService } from './semantic-service';
export { EmbeddingService } from './embedding-service';
export { ResearchService } from './research-service';
export { CitationService } from './citation-service';
export { ResearchTrendService } from './research-trend-service';
export { ObservatoryService } from './observatory-service';
export { BenchmarkService } from './benchmark-service';
export { PolicyService } from './policy-service';
export { DecisionService } from './decision-service';
export { ForecastService } from './forecast-service';
export { ForecastModelService } from './forecast-model-service';
export { CapacityForecastService } from './capacity-forecast-service';
export { AgentService } from './agent-service';
export { AgentTaskService } from './agent-task-service';
export { AgentMemoryService } from './agent-memory-service';
export { ExperimentService } from './experiment-service';
export { DatasetService } from './dataset-service';
export { MarketplaceService } from './marketplace-service';
export { SimulationService } from './simulation-service';
export { ScenarioService } from './scenario-service';
export { CopilotService } from './copilot-service';
export { IntelligenceDashboardService, type DashboardOverview, type CrossDomainInsight } from './intelligence-dashboard-service';