import z from "zod";

export const CreateLifelongLearningSchema = z.object({
  school_id: z.string().uuid({ message: "Identifiant de l'école invalide" }),
  user_id: z.string().uuid({ message: "Identifiant de l'utilisateur invalide" }),
  learning_title: z.string().min(1, { message: "Le titre de formation est requis" }).max(255, { message: "Le titre de formation ne doit pas dépasser 255 caractères" }),
  learning_type: z.enum(["course", "workshop", "seminar", "webinar", "certification", "self_study", "mentoring", "coaching", "other"], { message: "Type de formation invalide" }),
  provider: z.string().min(1, { message: "Le fournisseur est requis" }).max(255, { message: "Le fournisseur ne doit pas dépasser 255 caractères" }),
  category: z.enum(["academic", "professional", "technical", "soft_skills", "digital", "language", "leadership", "safety", "compliance", "other"], { message: "Catégorie invalide" }),
  status: z.enum(["enrolled", "in_progress", "completed", "dropped", "suspended", "expired"], { message: "Statut invalide" }).default("enrolled"),
  enrollment_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date d'inscription invalide" }),
  start_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date de début invalide" }).optional(),
  end_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date de fin invalide" }).optional(),
  completion_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date d'achèvement invalide" }).optional(),
  duration_hours: z.number().min(0, { message: "La durée doit être positive" }).max(9999, { message: "La durée est trop élevée" }).optional(),
  progress_percentage: z.number().min(0, { message: "Le pourcentage minimum est 0" }).max(100, { message: "Le pourcentage maximum est 100" }).default(0),
  score: z.number().min(0, { message: "Le score minimum est 0" }).max(100, { message: "Le score maximum est 100" }).optional(),
  credit_units: z.number().min(0, { message: "Les unités de crédit doivent être positives" }).max(999, { message: "Le nombre d'unités est trop élevé" }).optional(),
  credential_earned: z.boolean({ message: "Statut de credential invalide" }).default(false),
  credential_id: z.string().uuid({ message: "Identifiant du credential invalide" }).optional().nullable(),
  modules: z.array(z.object({
    module_id: z.string().uuid({ message: "Identifiant du module invalide" }),
    module_name: z.string().min(1, { message: "Le nom du module est requis" }),
    status: z.enum(["pending", "in_progress", "completed"], { message: "Statut du module invalide" }).default("pending"),
    score: z.number().min(0, { message: "Le score minimum est 0" }).max(100, { message: "Le score maximum est 100" }).optional(),
  })).optional(),
  funding_source: z.enum(["self_funded", "school", "government", "scholarship", "employer", "other"], { message: "Source de financement invalide" }).optional(),
  metadata: z.record(z.unknown()).optional(),
});

export const UpdateLifelongLearningSchema = z.object({
  learning_title: z.string().min(1, { message: "Le titre de formation est requis" }).max(255, { message: "Le titre de formation ne doit pas dépasser 255 caractères" }).optional(),
  learning_type: z.enum(["course", "workshop", "seminar", "webinar", "certification", "self_study", "mentoring", "coaching", "other"], { message: "Type de formation invalide" }).optional(),
  provider: z.string().min(1, { message: "Le fournisseur est requis" }).max(255, { message: "Le fournisseur ne doit pas dépasser 255 caractères" }).optional(),
  category: z.enum(["academic", "professional", "technical", "soft_skills", "digital", "language", "leadership", "safety", "compliance", "other"], { message: "Catégorie invalide" }).optional(),
  status: z.enum(["enrolled", "in_progress", "completed", "dropped", "suspended", "expired"], { message: "Statut invalide" }).optional(),
  enrollment_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date d'inscription invalide" }).optional(),
  start_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date de début invalide" }).optional().nullable(),
  end_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date de fin invalide" }).optional().nullable(),
  completion_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: "Date d'achèvement invalide" }).optional().nullable(),
  duration_hours: z.number().min(0, { message: "La durée doit être positive" }).max(9999, { message: "La durée est trop élevée" }).optional(),
  progress_percentage: z.number().min(0, { message: "Le pourcentage minimum est 0" }).max(100, { message: "Le pourcentage maximum est 100" }).optional(),
  score: z.number().min(0, { message: "Le score minimum est 0" }).max(100, { message: "Le score maximum est 100" }).optional(),
  credit_units: z.number().min(0, { message: "Les unités de crédit doivent être positives" }).max(999, { message: "Le nombre d'unités est trop élevé" }).optional(),
  credential_earned: z.boolean({ message: "Statut de credential invalide" }).optional(),
  credential_id: z.string().uuid({ message: "Identifiant du credential invalide" }).optional().nullable(),
  modules: z.array(z.object({
    module_id: z.string().uuid({ message: "Identifiant du module invalide" }),
    module_name: z.string().min(1, { message: "Le nom du module est requis" }),
    status: z.enum(["pending", "in_progress", "completed"], { message: "Statut du module invalide" }).default("pending"),
    score: z.number().min(0, { message: "Le score minimum est 0" }).max(100, { message: "Le score maximum est 100" }).optional(),
  })).optional(),
  funding_source: z.enum(["self_funded", "school", "government", "scholarship", "employer", "other"], { message: "Source de financement invalide" }).optional(),
  metadata: z.record(z.unknown()).optional(),
});
