export {
  CreateTeacherSchema,
  UpdateTeacherSchema,
  ArchiveTeacherSchema,
  RestoreTeacherSchema,
  DeleteTeacherSchema,
  AssignmentSchema,
  SubjectSchema,
  ScheduleSchema,
  AvailabilitySchema,
  ContractSchema,
  LeaveSchema,
  PayrollSchema,
  QualificationSchema,
  CertificationSchema,
  EvaluationSchema,
  TeacherMedicalSchema,
  EmergencyContactSchema,
  TeacherImportSchema,
  TeacherExportSchema,
  TeacherFiltersSchema,
  TeacherSearchSchema,
  TeacherStatisticsSchema,
  TeacherTimelineSchema,
} from './schemas';

export type {
  CreateTeacherInput,
  UpdateTeacherInput,
  ArchiveTeacherInput,
  RestoreTeacherInput,
  DeleteTeacherInput,
  AssignmentInput,
  SubjectInput,
  ScheduleInput,
  AvailabilityInput,
  ContractInput,
  LeaveInput,
  PayrollInput,
  QualificationInput,
  CertificationInput,
  EvaluationInput,
  TeacherMedicalInput,
  EmergencyContactInput,
  TeacherImportInput,
  TeacherExportInput,
  TeacherFiltersInput,
  TeacherSearchInput,
  TeacherStatisticsInput,
  TeacherTimelineInput,
} from './schemas';
