'use client';

import { useState, useEffect } from 'react';
import RoleLayout from '@/components/layout/RoleLayout';
import { getSupabase } from '@/lib/api/shared';
import { useAuth } from '@/hooks/useAuth';
import { Sparkles, TrendingUp, AlertTriangle, CheckCircle, Clock, ArrowRight, Loader2 } from 'lucide-react';

export default function AIStudyPlanPage() {
  const { user } = useAuth();
  const [plan, setPlan] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const supabase = getSupabase();
        const { data, error } = await supabase
          .from('study_plans')
          .select('*')
          .eq('user_id', user?.id)
          .eq('status', 'active')
          .order('created_at', { ascending: false })
          .limit(1)
          .single();
        if (error && error.code !== 'PGRST116') throw error;
        setPlan(data);
      } catch (e) {
        console.error('[AI Study Plan] Failed to load plan:', e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [user?.id]);
  return (
    <RoleLayout role="admin" breadcrumbs={[{ label: 'AI' }, { label: 'Study Plan' }]}>
      <div className="flex justify-between items-end mb-8">
        <div>
          <span className="text-xs font-bold text-[#3525cd] uppercase tracking-widest flex items-center gap-2">
            <Sparkles size={14} /> Generated by Awa AI
          </span>
          <h2 className="text-3xl font-bold text-[#191c1d] mt-1">Your Recommended Study Plan</h2>
          <p className="text-[#464555] mt-2 max-w-xl">A personalized roadmap optimized for your upcoming exams in Advanced Calculus and Macroeconomics.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        {/* Main Plan */}
        <div className="md:col-span-8 space-y-6">
          {/* Monday */}
          <div className="bg-white rounded-xl p-6 shadow-card relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-[#3525cd]" />
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-xl font-bold text-[#191c1d]">Monday, Oct 23</h3>
                <p className="text-sm text-[#464555]">Focus: Foundations & Logic</p>
              </div>
              <div className="text-right">
                <span className="text-lg font-bold text-[#3525cd]">2.5h</span>
                <p className="text-[10px] uppercase font-bold text-[#464555]">Estimated</p>
              </div>
            </div>
            <div className="space-y-3">
              {[
                { icon: '📐', name: 'Multivariable Limits', desc: 'Video + 5 Problems' },
                { icon: '📈', name: 'IS-LM Model Deep Dive', desc: 'Review Quiz 2 mistakes' },
              ].map((task) => (
                <div key={task.name} className="flex items-center gap-3 p-3 bg-[#f3f4f5] rounded-xl">
                  <span className="text-xl">{task.icon}</span>
                  <div className="flex-1">
                    <p className="font-bold text-[#191c1d] text-sm">{task.name}</p>
                    <p className="text-xs text-[#464555]">{task.desc}</p>
                  </div>
                  <ArrowRight size={16} className="text-[#c7c4d8]" />
                </div>
              ))}
            </div>
          </div>

          {/* Wednesday */}
          <div className="bg-white rounded-xl p-6 shadow-card relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-[#0060ac]" />
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-xl font-bold text-[#191c1d]">Wednesday, Oct 25</h3>
                <p className="text-sm text-[#464555]">Focus: Macro Policy Analysis</p>
              </div>
              <span className="text-lg font-bold text-[#0060ac]">3h</span>
            </div>
            <div className="flex items-center gap-3 p-3 bg-[#f3f4f5] rounded-xl">
              <span className="text-xl">🏛️</span>
              <div className="flex-1">
                <p className="font-bold text-[#191c1d] text-sm">Monetary Policy Transmission</p>
                <p className="text-xs text-[#464555]">Interactive Simulation Module</p>
              </div>
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="md:col-span-4 space-y-6">
          <div className="bg-[#2e3132] text-white p-6 rounded-xl">
            <Sparkles size={24} className="text-[#e2dfff] mb-3" />
            <h3 className="font-bold mb-2">Smart Insights</h3>
            <p className="text-sm text-slate-300 leading-relaxed">
              &ldquo;You perform 22% better in Calculus when studying before 10 AM. I&apos;ve shifted your math blocks to mornings.&rdquo;
            </p>
          </div>

          <div className="bg-[#e7e8e9] p-6 rounded-xl">
            <h3 className="font-bold text-[#191c1d] mb-4 flex items-center gap-2">
              <AlertTriangle size={16} className="text-[#ba1a1a]" /> Priority Review
            </h3>
            <div className="space-y-3">
              {[
                { name: 'Chain Rule (Calc)', pct: 65, color: 'bg-[#ba1a1a]' },
                { name: 'Fiscal Multipliers', pct: 72, color: 'bg-[#0060ac]' },
              ].map((item) => (
                <div key={item.name} className="p-3 bg-white rounded-lg">
                  <div className="flex justify-between text-[10px] font-bold text-[#464555] mb-1">
                    <span>{item.name}</span><span>{item.pct}% ACCURACY</span>
                  </div>
                  <div className="h-1.5 bg-[#e7e8e9] rounded-full overflow-hidden">
                    <div className={`h-full ${item.color} rounded-full`} style={{ width: `${item.pct}%` }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </RoleLayout>
  );
}
