import type {
  ExecutiveDashboard,
  AcademicAnalytics,
  FinancialAnalytics,
  HrAnalytics,
  StudentAnalytics,
  TeacherAnalytics,
  ParentAnalytics,
  PredictiveAIResult,
  Prediction,
  ReportConfig,
  CustomDashboard,
  DashboardWidget,
  ChartData,
  GeoMapData,
  HeatmapData,
  FunnelData,
  ScheduledReport,
  DataWarehouseFact,
  DataWarehouseDimension,
  ETLJob,
  AnalyticsPeriodType,
  ChartTypeEnum,
  ExportFormatType,
  DataSourceTypeEnum,
  PredictiveModelType,
  ReportScheduleType,
  AnalyticsRepository,
} from '@educi/types';

export interface AnalyticsRepositoryExtended extends AnalyticsRepository {
  logAnalyticsEvent(schoolId: string, event: string, data: Record<string, unknown>): Promise<void>;
}

export type {
  ExecutiveDashboard,
  AcademicAnalytics,
  FinancialAnalytics,
  HrAnalytics,
  StudentAnalytics,
  TeacherAnalytics,
  ParentAnalytics,
  PredictiveAIResult,
  Prediction,
  ReportConfig,
  CustomDashboard,
  DashboardWidget,
  ChartData,
  GeoMapData,
  HeatmapData,
  FunnelData,
  ScheduledReport,
  DataWarehouseFact,
  DataWarehouseDimension,
  ETLJob,
  AnalyticsPeriodType,
  ChartTypeEnum,
  ExportFormatType,
  DataSourceTypeEnum,
  PredictiveModelType,
  ReportScheduleType,
};
